### ISSUE TITLE
Change color of all molecule

### ISSUE THREAD

**Issue by hellhorse123** [nglviewer/ngl#1004]
I trying to change color in React component of all Molecule, but useEffect is not updating when color is chenging. Maybe someone implemented something like this because I didn’t find any examples of changing the color of the entire molecule.
This is my component code:

```
import { useEffect, useRef, useState } from 'react';
import * as NGL from 'ngl';
const MoleculeViewer = ({ pdbId = '4hhb' }) => {
  const ref = useRef();
  const [color, setColor] = useState('default');
  const [loadedComponent, setLoadedComponent] = useState(null);
  const [representation, setRepresentation] = useState(null);

  useEffect(() => {
    const stage = new NGL.Stage(ref.current);

    stage.loadFile(`rcsb://${pdbId}`).then((o) => {
      setLoadedComponent(o);
      const rep = o.addRepresentation('cartoon', { color });
      setRepresentation(rep);  // Store the representation
      o.autoView();
    }).catch(error => {
      console.error("Error loading the molecule:", error);
    });

    return () => {
      if (stage && loadedComponent) {
        stage.removeComponent(loadedComponent);
      }
    };
  }, [pdbId]);

  useEffect(() => {
    if (loadedComponent && representation) {
      // Remove the old representation
      loadedComponent.removeRepresentation(representation);

      // Add a new representation with the updated color
      const newRepresentation = loadedComponent.addRepresentation('cartoon', { color });
      setRepresentation(newRepresentation);
    }
  }, [color, loadedComponent]);

  const handleChangeColor = () => {
    setColor('green');
  };

  return (
    <div>
      <div ref={ref} style={{ width: '500px', height: '500px' }} />
      <button onClick={handleChangeColor}>Change Color to Green</button>
    </div>
  );
};

export default MoleculeViewer;
```

**Comment by ppillot** [comment]
At first look, I am not sure why this does not work except that I know React state variables (from `useState`) can introduce some issues with the objects they contain, because React ensures that the variable it holds remains unchanged while the rendering function is being executed. This means that the state variable `representation` might be disconnected from the objects that are stored in NGL.
In my experience this also leads to memory leaks, so I'd recommend to never store NGL objects (such as representations, components and stage) in react useState, and instead storing them using a React reference (`useRef`).
In the code you've posted, the part `loadedComponent.removeRepresentation(representation);` should remove the representation object from NGL, but I've seen cases where some part of the representation object remains in the component because React is still holding a reference and the object cannot be cleared properly.

The code could be simplified by not removing/adding back the cartoon representation and just changing its parameters using a call like `representation.setParameters({color: 'green'})`.
I would suggest to hold `representation` and `loadedComponent` in a ref.
Lastly, the cleaning function should also take care of the stage (using the `.dispose()` method) which should avoid memory leaks when the `pdbId` prop changes in the parent component.


```javascript
import { useEffect, useRef, useState } from 'react';
import * as NGL from 'ngl';
const MoleculeViewer = ({ pdbId = '4hhb' }) => {
  const ref = useRef();
  const representation = useRef(null);

  useEffect(() => {
    const stage = new NGL.Stage(ref.current);
    
    stage.loadFile(`rcsb://${pdbId}`).then((o) => {
      const rep = o.addRepresentation('cartoon', { color });
      representation.current = rep;  // Store the representation
      o.autoView();
    }).catch(error => {
      console.error("Error loading the molecule:", error);
    });

    return () => {
      if (stage) {
        stage.dispose();
      }
    };
  }, [pdbId]);

  const handleChangeColor = () => {
    representation.current?.setParameters({color: 'green'});
  };

  return (
    <div>
      <div ref={ref} style={{ width: '500px', height: '500px' }} />
      <button onClick={handleChangeColor}>Change Color to Green</button>
    </div>
  );
};

export default MoleculeViewer;
```

**Comment by hellhorse123** [comment]
By the way, in your code I see the implementation:
```
 return () => {
      if (stage) {
        stage.dispose();
      }
    };
```

when I call this in my code, I get error:
```
Error loading the molecule: TypeError: Cannot read properties of undefined (reading 'length')
    at Signal3.dispatch (signals.js:367:36)
    at Signal3.dispatch  ...

```
and the model doesn't load at all.
I came across advice to use the `stage.removeComponent()` method.

Could you please tell me what this error is?
<img width="1438" alt="Screenshot 2023-12-04 at 20 36 17" src="https://github.com/nglviewer/ngl/assets/48678379/ca718f18-adb4-4b9c-9133-e98b1238dab2">

**Comment by papillot** [comment]
There is an error in the code I've suggested where `color` is not defined.
```javascript
stage.loadFile(`rcsb://${pdbId}`).then((o) => {
      const rep = o.addRepresentation('cartoon', { color: 'green' });
      representation.current = rep;  // Store the representation
      o.autoView();
    })
```

Regarding the `.dispose` method, I've looked at what I use in a React implementation to address this issue and there is a bit more boiler plate code:
```javascript
stage.viewer.wrapper.remove(); // div wrapper generated by NGL. Hides the subsequent stages if not removed
stage.viewer.renderer.forceContextLoss();
stage.dispose();
```

**Comment by hellhorse123** [comment]
> There is an error in the code I've suggested where `color` is not defined.
> 
> ```js
> stage.loadFile(`rcsb://${pdbId}`).then((o) => {
>       const rep = o.addRepresentation('cartoon', { color: 'green' });
>       representation.current = rep;  // Store the representation
>       o.autoView();
>     })
> ```
> 
> Regarding the `.dispose` method, I've looked at what I use in a React implementation to address this issue and there is a bit more boiler plate code:
> 
> ```js
> stage.viewer.wrapper.remove(); // div wrapper generated by NGL. Hides the subsequent stages if not removed
> stage.viewer.renderer.forceContextLoss();
> stage.dispose();
> ```

During the first page load, I get the following error (see picture)
<img width="428" alt="Screenshot 2023-12-06 at 07 59 44" src="https://github.com/nglviewer/ngl/assets/48678379/1e8983c5-c226-46eb-84b4-44f10f96b487">

, but the model loads and seems to work correctly. Right now my code looks like this:

```
import { useEffect, useRef } from "react";
import * as NGL from "ngl";
// eslint-disable-next-line react/prop-types
const MoleculeViewer = ({ pdbId = "4hhb" }) => {
  const ref = useRef();
  const representation = useRef(null);

  useEffect(() => {
    const stage = new NGL.Stage(ref.current);
    stage
      .loadFile(`rcsb://${pdbId}`)
      .then(function (o) {
        console.log("Loaded object:", o); // For debugging
        const rep = o.addRepresentation("cartoon", { defaultRepresentation: true });
        representation.current = rep;
        o.autoView();
      })
      .catch((error) => {
        console.error("Error loading the molecule:", error);
      });

    return () => {
      if (stage) {
        stage.viewer.wrapper.remove(); // div wrapper generated by NGL. Hides the subsequent stages if not removed
        stage.viewer.renderer.forceContextLoss();
        stage.dispose();
      }
    };
  }, [pdbId]);

  const handleChangeColor = () => {
    representation.current?.setParameters({ color: "green" });
  };

  return (
    <div>
      <div ref={ref} style={{ width: "500px", height: "500px" }} />
      <button onClick={handleChangeColor}>Change Color to Green</button>
    </div>
  );
};

export default MoleculeViewer;
```
