### ISSUE TITLE
Issue(s) with release 2.2.1 (e.g: custom color doesn't work)

### ISSUE THREAD

**Issue by hainm** [nglviewer/ngl#1010]
Hi,

# custom color
While I am testing NGL 2.2.1 for `nglview` (https://github.com/nglviewer/nglview/pull/1086) , I find that the custom color doesn't work anymore

<img width="1496" alt="image" src="https://github.com/nglviewer/ngl/assets/4451957/b6d0612b-17e2-4545-b557-3287663c4d34">

**Comment by ppillot** [comment]
Thanks for reporting this. I've noticed the same issue in a separate branch and did not realize it was still in production.

**Comment by hainm** [comment]
Thanks @ppillot. I look forward for the fix.

**Comment by ppillot** [comment]
@hainm fix has been published to npm as v2.2.2

**Comment by hainm** [comment]
@ppillot I confirm the fix does work. Thank you so much, Paul.
