### ISSUE TITLE
RCSB is deprecating MMTF file format and will stop serve it in July 2024

### ISSUE THREAD

**Issue by papillot** [nglviewer/ngl#1015]
https://www.rcsb.org/news/feature/65a1af31c76ca3abcc925d0c

Recommended way would be to support BinaryMMCIF instead.

**Comment by papillot** [comment]
Working on this at the moment,
I've noticed that mmCIF and  binary cif files from RCSB do not contain the connectivity information in contrast with MMTF files (and PDB files when it comes to heteroatoms).
The workaround would be to use the "Updated mmCif files" from PDBe which contain the chem_comp_bond table for all the residues present in the data block.
https://preview.rbvi.ucsf.edu/chimerax/docs/devel/modules/mmcif/mmcif_guidelines.html#:~:text=Europe%E2%80%99s-,updated%20mmCIF%20files,-%2C%20currently%20do%20not

**Comment by ppillot** [comment]
Solved with #1040
