### ISSUE TITLE
An option to hide intra-protein non-bonded interactions would be nice [feature request]

### ISSUE THREAD

**Issue by UnixJunkie** [nglviewer/ngl#1017]
At rcsb.org, in the Ligand View tab, it would be nice to have an option (maybe even ON by default),
to hide intra-protein non-bonded interactions.
Because, when  you are in the Ligand View tab, it means you are interested in protein-ligand interactions.
All the rest is just visual clutter.
 
E.g. go to https://www.rcsb.org/3d-view/ngl/5ufx ->
Structure tab -> Choose the NGL viewer -> Ligand View tab -> choose any of the two ligands (86Y id).

**Comment by ppillot** [comment]
NGL contact representations have a `filterSele` property which allows to restrict the sets between which contacts are harvested. This property can be a string or a tuple of strings. In the latter case the contacts must satisfy being between entities from each set.

The NGL implementation at rcsb.org is not part of this project, so there is nothing more we could do regarding your feature request in the context of RCSB.
