### ISSUE TITLE
dispose() method leaves part of the old representation when changing model

### ISSUE THREAD

**Issue by hellhorse123** [nglviewer/ngl#1019]
On the 3D model in React I have several pocket sizes. When I change the size (load different files), the default representation remains on the 3D scene, going beyond the scope of the smaller model (pictures 1/2):
<img width="525" alt="Screenshot 2024-01-26 at 09 59 58" src="https://github.com/nglviewer/ngl/assets/48678379/f0312474-6de6-476d-9623-911c7c1bf858">
<img width="437" alt="Screenshot 2024-01-26 at 10 00 19" src="https://github.com/nglviewer/ngl/assets/48678379/e2e263c5-a02f-4cd4-b478-2dba748ba628">

Part of Code:

```
import React, { useState, useEffect, useRef, useContext, useMemo } from "react";
...
  const stageRef = useRef();
...
  useEffect(() => {
    const stage = stageRef.current;
    if (stage) {
      // Clear old representations
      pocketReps.current.forEach(rep => {
        if (rep) {
          rep.dispose(); // Dispose each representation
        }
      });
      pocketReps.current = [];

      // Load new pocket data
      memoizedPocketData.forEach((pocket) => {
        if (pocket && typeof pocket !== "undefined") {
          
          stage
            .loadFile(pocket.url, { defaultRepresentation: true })
            .then((o) => {
              const rep = o.addRepresentation("surface", { color: pocket.color });
              pocketReps.current.push(rep); // Track the new representation
              o.autoView();
            })
            .catch((error) => console.error("Error loading pocket file:", error));
        }
      });
    }
  }, [memoizedPocketData]);
```

**Comment by fredludlow** [comment]
I think you need to call `removeRepresentation` on the component (which will call dispose: https://github.com/nglviewer/ngl/blob/master/src/component/component.ts#L308)

**Comment by ppillot** [comment]
Note also that former components are not removed from the stage with this implementation.
A representation is attached to a given components. Each time the `stage.loadFile` promise returns, a new component is created, for which your code creates multiple representations (the default one, apparently only ball+stick representation, and the surface representation).
