### ISSUE TITLE
info in tooltip

### ISSUE THREAD

**Issue by hellhorse123** [nglviewer/ngl#1024]
How to change info, which displays in default tootlip?
For example, I want to delete filename of atom
<img width="511" alt="Screenshot 2024-02-20 at 10 56 26" src="https://github.com/nglviewer/ngl/assets/48678379/07508bf1-b652-48ba-b83b-e7fb7615f1cd">

**Comment by ppillot** [comment]
It can't be configured: https://github.com/nglviewer/ngl/blob/d242234becffbe91c11126079ed22e6930390584/src/controls/picking-proxy.ts#L310

But this would be a nice feature to add (using the same templating syntax as for labels)

**Comment by hellhorse123** [comment]
I found a workaround: you can rename the file itself and this solves my problem:

`component.structure.name = "Protein";`
<img width="379" alt="Screenshot 2024-04-26 at 13 03 57" src="https://github.com/nglviewer/ngl/assets/48678379/eae43b36-2f3e-4349-9fb9-0532330e8519">
