### ISSUE TITLE
displaying hydrogens as ligands

### ISSUE THREAD

**Issue by hellhorse123** [nglviewer/ngl#1038]
After adding hydrogens to the complex, ngl begins to display not only ligands when sele:ligand :
![telegram-cloud-photo-size-2-5253472957471250904-y](https://github.com/nglviewer/ngl/assets/48678379/3797895b-7cfa-4862-a181-843120dd2b1a)

but Molstar doesn't do that:

![telegram-cloud-photo-size-2-5253472957471250903-y](https://github.com/nglviewer/ngl/assets/48678379/a9c44ef4-3b5a-4688-b4af-a15fab529aa7)
How to achieve behavior like a Molstar?

**Comment by papillot** [comment]
It probably depends on how the information from the file that is used is encoded.
Maybe paste an excerpt of the corresponding PDB file before and after so that we could understand what's happening.
My guess is that the PDB file now contains HETATM records instead of ATOM records

**Comment by ppillot** [comment]
Closing this issue as non reproducible

**Comment by subinoyprescience** [comment]
How to add hydrogen and remove hydrogen if present in the structure?

**Comment by papillot** [comment]
NGL can't do modeling, that is, it can't add hydrogens.
It's possible to hide the hydrogens if they are present using `setSelection` at the level of the component for example
```
component.setSelection('not _H')
```

**Comment by subinoyprescience** [comment]
Okay thank you so much, it's working.
