### ISSUE TITLE
loading ply file error

### ISSUE THREAD

**Issue by vvishwesh** [nglviewer/ngl#1049]
I am trying to load a surface in .PLY format into NGLView. I get the following error in the browser "Uncaught (in promise) error loading file: 'Error: autoLoad: ext 'ply' unknown". Any ideas on where I am going wrong. I thought ply was supported by NGL.  

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <style>
            * { margin: 0; padding: 0; } 
            html, body { 
                width: 100%; 
                height: 100%; 
                overflow: hidden; 
            }

        </style>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ngl/2.3.0/ngl.js"></script>  
    </head>
    <body>

        <script>
            document.addEventListener("DOMContentLoaded", function () 
            {

                // Create NGL Stage object
                var stage = new NGL.Stage("viewport");
                //stage.loadFile("rcsb://1crn", {defaultRepresentation: true});

                ///*
                stage.loadFile("https://raw.githubusercontent.com/nglviewer/ngl/master/data/1crn.pdb").then(function (o) {
                    o.addRepresentation("spacefill")
                    o.autoView()
                })

                stage.loadFile("https://raw.githubusercontent.com/nglviewer/ngl/master/data/1crn.ply").then(function (o) {
                        o.addRepresentation("surface", {
                        opacity: 0.7, side: "double"
                    })
                })
                //*/

            });

        </script>
        <div id="viewport" style="width:100%; height:100%;"></div>
    </body>
</html>

**Comment by ppillot** [comment]
Yes, that's a known regression.
The code had to be updated in the last month to upgrade Three.js dependency and this caused breakages in the Ply reader code which used deprecated Three.js constructs. Due to time constraints the support for Ply format was removed, but any PR is welcome to add back support for PLY format.

**Comment by fredludlow** [comment]
Should be reinstated in v2.4.0
