### ISSUE TITLE
Name representations to toggle on/off later

### ISSUE THREAD

**Issue by pguillem** [nglviewer/ngl#1051]
Hello there,
Say you add a representation like this:

`o.addRepresentation("ribbon",  {sele: "all and (not hydrogen)", color: "element", colorValue: "red", opacity: 0.2});`

I'm superposing 5 or 10 PDB files, each with 2 representations. 
I'm trying to think of an array of pointers to the representations, so that i can toggle on/off these representations with buttons.

Is there a value or reference I can store in the array, so that I can cast a show/hide toggle on a specific representation? 
Is there a parameter in the addRepresentation() function that I need to set to make it unique?
If so, how do I access that specific representation later (to toggle it) inside the NGL object?

It is not very clear in the docs.

Thanks in advance
Pedro

**Comment by ppillot** [comment]
One you have given a name to a representation (e.g. `myName`), you can access it using `stage.getRepresentationsByName('myName')`, which returns a collection of all representations that have the name `myName`. `.first` property gives you access to the first representation in the collection (useful if you know there is only one that has the name `myName`, while `forEach` allows to iterate over all the representations in the collection.
