### ISSUE TITLE
Transparent point representation visible on top of other representations

### ISSUE THREAD

**Issue by jamesfoley** [nglviewer/ngl#598]
I currently have an issue where my transparent point representation is visible over the top of other representations.

![Image](https://i.imgur.com/yImh0ip.png)

As you can see in the image above, the transparent points are basically punching a hole into the green representation behind it. I understand NGL doesn't support multi layer transparency which is probably what I'm running into here, but is it possible to just have the point not render at all, but still be pickable?

I'm using the point representation as a reliable way to pick atoms using the line representation, but just want it to be invisible.

**Comment by fredludlow** [comment]
I don't think you can pick anything with opacity < 0.3 (https://github.com/arose/ngl/blob/master/src/shader/Point.frag#L36). I haven't tried changing that number?
#569 might fix your problem when it's merged? (it makes it quite a lot easier to pick line representations)

**Comment by jamesfoley** [comment]
Ah interesting, I definitely have opacity set to 0 but am still able to pick it.

#569 certainly looks promising, at least in the example picking the line representation is much easier. Will probably hold out for this as it is much cleaner than using a hidden representation for it.
