### ISSUE TITLE
Functional TypeScript definitions

### ISSUE THREAD

**Issue by ktamiola** [nglviewer/ngl#678]
Hello ladies and gents. I am trying to compile a very simple StencilJS component, which would eventually render a PDB structure using `ngl`.

Does anybody has an access to functional TypeScript definitions, which would make executing the 'demo' script below, possible?

```javascript
      var stage = new NGL.Stage( "viewport" );
      stage.loadFile( "rcsb://1crn", { defaultRepresentation: true } );
```

**Comment by arose** [comment]
read #493 for the current state of TS and NGL
