### ISSUE TITLE
spin animation around axis relative to object

### ISSUE THREAD

**Issue by Oeffner** [nglviewer/ngl#700]
Is it possible to spin an object around a vector relative to the object? I try using 

`stage.spinAnimation.axis.set(0, 1, 0);`
`stage.setSpin(true);`
which animates spinning my model around what appears to be the Y axis with respect to the screen. But this is irrespective to how I rotate the object with the mouse during animation. Is it possible to do a spin animation around a vector with respect to the models own coordinate system?

**Comment by fredludlow** [comment]
Rather late to respond here, but for future reference:
stage.loadFile("/path/to/file").then(function(c) {
  stage.animationControls.spinComponent(c, [1,0,0])
})

See: http://nglviewer.org/ngl/api/class/src/controls/animation-controls.js~AnimationControls.html#instance-method-spinComponent

**Comment by Oeffner** [comment]
Thank you for looking into this. I just tested the spinComponent function. It seems that the specified rotation axis is not fixed to the molecule as it will change arbitrarily when rotating the molecule with the mouse.
