### ISSUE TITLE
Optimizing assembly surface geometry

### ISSUE THREAD

**Issue by garyo** [nglviewer/ngl#721]
If you load, for example, PDB 1d3e into NGL viewer, you get a nice surface representation of the 60-way symmetric assembly. I'm working on exporting the graphics from NGL, and I'd like to optimize the result so it has as little duplication as possible. I'm mostly just looking for some pointers to get started. For instance, if I want to reuse the same basic unit and instance and transform it to the other copies, where would I look to start that work?
I also suspect there's more than one copy of the actual mesh -- there certainly is in my resulting glTF export, but that could be something I'm doing wrong.
Any pointers or ideas would be helpful!

**Comment by fredludlow** [comment]
@garyo - I'm guessing you figured out a way to do this? If not, please reopen!
