### ISSUE TITLE
Trying to import postprocessing modules from three.js examples

### ISSUE THREAD

**Issue by giagitom** [nglviewer/ngl#730]
Hi, 
I would like to import EffectComposer and RenderPass modules from three.js to make some postprocessing effects. But I am having problems with the import statement i used:
```import {EffectComposer,RenderPass} from '../../node_modules/@types/three'```

It gives an error with rollup:
```[!] Error: Could not resolve '../../node_modules/@types/three'
Error: Could not resolve '../../node_modules/@types/three' from build/js/src/viewer/viewer.js
    at error (/home/gianluca/SOFT/GIT/ngl/node_modules/rollup/dist/rollup.js:3365:15)
    at /home/gianluca/SOFT/GIT/ngl/node_modules/rollup/dist/rollup.js:21484:25
    at async Promise.all (index 2)
    at async Promise.all (index 6)
    at async Promise.all (index 8)
    at async Promise.all (index 0)
```
Is there a correct way to import this modules?

**Comment by fredludlow** [comment]
Hi @giagitom - did you get anywhere with this?

**Comment by giagitom** [comment]
Hi @fredludlow yes, the previous three.js update solved the problem. Forgot to close this issue.

**Comment by garyo** [comment]
Hi @giagitom ; I'm also working on the same thing. It appears to me that NGL will need a bit of adjustment to work with EffectComposer/RenderPass because of how it renders the background and model separately, and also the supersampling; do you have it working?

**Comment by giagitom** [comment]
Hi @garyo , yes I have been able to implement postporcessing with renderpass. I integrated successfully outlines and ssao and a few other effects, but i had to disable supersampling for the moment. 
Here an example 
https://3dproteinimaging.com/protein-imager/?fetch=2e4a

**Comment by garyo** [comment]
Cool -- I agree, I was able to get it working as well, with a custom RenderPass. For supersampling, I think some minor changes to NGL viewer.ts are required; I'll post a PR soon (once I get color management figured out).
Your example looks really great! Love that NPR rendering.

**Comment by giagitom** [comment]
Thank you! Supersampling wasn't a priority for me but I think labels representation could benefit very much from it. 
Ssao is a cheap method but I think it gives really impressive results. 
I implemented also outlines only style, grayscale and flat coloring (at representation level). Fog isn't perfect though..

**Comment by luxaritas** [comment]
@garyo or @giagitom, would you mind sharing how you went about actually integrating with the EffectComposer? I see [the addition of the renderTarget to render()](https://github.com/eternagame/ngl/blob/094d5121d45cf1ec2746cfc0243041d8cbf68372/src/viewer/viewer.ts), but render is called automatically by animate, requestRender, etc. How exactly did you get the render to initiate from the composer? Monkeypatching?
