### ISSUE TITLE
tube representation and radiusData

### ISSUE THREAD

**Issue by rsakai** [nglviewer/ngl#735]
#453 mentions **radiusData** as one of renamed parameters. Is it possible to change the radius of tube representation based on the value provided separately?  Like specifying a custom color scheme? I understand you can set to "bfactor", but is it possible to define custom values per residue?

**Comment by fredludlow** [comment]
I made a quick example here:
https://codepen.io/fludlow/pen/BaoKjqx

`radiusData` is a mapping from atomIndex -> radius. It also requires the `radiusType` to be set to data

For completeness, here's the example code
```javascript
// Generate some fake radii {resno : r} - 1crn has 46 resiudes
// These would be the values you've calculated separately
const residueRadii = {}
for (let i=1; i<=46; i++){
    residueRadii[i] = 0.5 + Math.random()
}

// Load PDB entry 1CRN
stage.loadFile( "rcsb://1crn").then(c => {
    const radiusData = {}
    c.structure.eachAtom(ap=> {
        radiusData[ap.index] = residueRadii[ap.resno]    
    })
    c.addRepresentation('tube', {radiusType: 'data', radiusData: radiusData})
});

```
