### ISSUE TITLE
Volume Map with boxsize and transform problem

### ISSUE THREAD

**Issue by DAlvGar** [nglviewer/ngl#756]
Hi all!

I am trying to display two proteins and their electron density maps superposed. I have a transformation matrix for the structure that i also apply to the map. Everything works well if you display all the density map. However if I use boxSize to clip around the scene center 10Angstroms, the transformed volume map is then displaying in its original position (clipped) and not following the scene center.

Here's a picture, the orange maps should be on top of the blue one and clipped the same way.

![image](https://user-images.githubusercontent.com/15227264/83229957-3204fa80-a189-11ea-9199-9a85b4788e21.png)

I checked the settings and for both of them i have the same boxCenter and position, same boxSize, except for one of them that has a transform. If i unset boxSize, the map is correctly ovelapped again.

Do you have any idea of what the issue might be? Where in the code could I look? 

Thanks guys!

**Comment by DAlvGar** [comment]
If this helps, i found out that its actually moving, but it seems in the oposite direction. Maybe some sign issue? 

![ezgif com-crop](https://user-images.githubusercontent.com/15227264/83237489-47802180-a195-11ea-84f1-f4e27f925b7c.gif)

**Comment by fredludlow** [comment]
Hi @DAlvGar, the inverse transform wasn't being applied to boxCenter (so it was calculating boxCenter from the screen assuming no transform, creating the cut-out map at that position and then transforming the output correctly). Should be fixed as part of #769

**Comment by DAlvGar** [comment]
Thanks q lot @fredludlow !!
