### ISSUE TITLE
Embedding ngl in reveal.js

### ISSUE THREAD

**Issue by jamesETsmith** [nglviewer/ngl#770]
## Goal

To embed an arbitrary number of nglviewers in a `reveal.js` presentation

## Problem
At the moment I can embed two viewers without issue, but typically as soon as I try to embed more than two I start running into problems. By that I mean, panes will show up blank, and when I refresh the page the embedded viewer looks fine _but_ other panes are now blank/flashing.

## Minimal Example
https://codepen.io/jamesetsmith/pen/VweJjNB

**Comment by hainm** [comment]
@jamesETsmith I don't have an answer for you, but just in case you want to look at @arose 's talk slides. https://github.com/arose/arose.github.io/tree/master/talks/ngl-web3d

I think @arose has some tricks in that.

**Comment by garyo** [comment]
Also please try the latest github master and import ngl's new ESM module. This avoids the issue where you could have multiple copies of three.js (which ngl depends on). Multiple copies of three.js can lead to the kinds of graphics issues you're describing. It could be something else, but that's the first thing to check.

**Comment by jamesETsmith** [comment]
@hainm and @garyo thanks for your help. I apologize if my questions are a bit basic, I don't have a lot of experience with HTML or JS. 

@garyo by importing ESM do you mean adding something like the following?

```html
	<script type="module">
		import { esm } from "/home/james/apps/ngl/dist/ngl.esm.js";
	</script>
```

I tried this and the results are the same. Is there any way I can test to see if there are multiples copies of three.js that get loaded?

**Comment by jamesETsmith** [comment]
Sorry for that last question, like I said I'm still very new to HTML/JS. I've got a [minimal example](https://codepen.io/jamesetsmith/pen/VweJjNB) where I load `Stage` from the ngl module, but the problem persists. @garyo do you have any other ideas to try?

**Comment by garyo** [comment]
Hi James; no worries. I see the same error as you when I try your example. There isn't a release available on unpkg yet where three.js is decoupled from NGL, so if the three.js issue is what's causing this, you'd have to use github master. But I'm not sure that it is -- just an idea. Alternatively, you could try adding `stage.dispose()` when a molecule goes out of view. I don't know reveal.js, so I'm not sure what it's doing. Give that a try.

**Comment by jamesETsmith** [comment]
Hi @garyo, when using `ngl.esm.js` from the latest commit I still see the problem. I tried adding `stage.dispose()` but I can't figure out a way to make it work with `reveal.js` where I dispose of the stage when I leave a slide.

**Comment by fredludlow** [comment]
The example @hainm linked is live here:
http://nglviewer.org/talks/ngl-web3d/index.html
(source code: https://github.com/arose/arose.github.io/tree/master/talks/ngl-web3d)

That has a single viewport element and a single stage instance which sits outside of the slides:

```html
<body>
<div class="reveal">
<div class="slides">

<small id="busy" style="display:none; position:absolute; top:0px; right:0px;">Loading...</small>
<div id="viewport" style="width:960px; height:700px;"></div>

<!-- SNIP -->
<section data-state="slide-loading">
    <h2 id="status">Loading...</h2>
</section>
```

And a bunch of event listeners that trigger on different slides loading and reuse the same stage, e.g.

```javascript
Reveal.addEventListener( "slide-3j3q-1", function(){
    stage.setParameters( { sampleLevel: -1 } );
    hideAll();
    ...
```

There's another example here:
http://nglviewer.org/talks/ngl-vizbi/

Again, this re-uses a single instance for the 'wall' slide and another single instance for everything else.

I don't think there's any call to `dispose` anywhere here, just some fancy DOM manipulation to re-use the same stage instance.

**Comment by jamesETsmith** [comment]
I've gotten things working, thank you everyone! I took a slightly different approach than in the slides posted by @hainm and @fredludlow. I didn't like using the same stage and wiping it clean every time so I create the stages one at a time as the slide comes up (which also deletes them as the slide goes out of view). 

There's a minimal example here: https://codepen.io/jamesetsmith/pen/wvGBRyE

I also needed to put multiple on the same screen and created a minimal working example for that based on the presentation (http://nglviewer.org/talks/ngl-vizbi/) that @fredludlow shared: https://codepen.io/jamesetsmith/pen/xxVbmzE?editors=1000

Thanks again for all your help!

**Comment by fredludlow** [comment]
That's great, and thanks for example, we should add a link from the docs.

>

**Comment by jamesETsmith** [comment]
@fredludlow, I'm happy to make a PR if you tell me where you'd prefer to put them. I think they'd be best in the [embedding](http://nglviewer.org/ngl/api/manual/usage/embedding.html), but let me know if you think my examples would fit better somewhere else.

**Comment by fredludlow** [comment]
That would be great, and yes, the embedding section looks like a good place.
