### ISSUE TITLE
show multi protein and select especial Amino acid

### ISSUE THREAD

**Issue by AlirezaDoustmohammadi** [nglviewer/ngl#772]
Hello.
How I can show multi-protein on ngl viewer? for example, I want to show native protein and mutated protein at the same view and compare them. 
is it possible to show protein Amino acids at the bottom of the view and select it and focus on (same as YASARA viewer)?

**Comment by fredludlow** [comment]
You can certainly load mutliple files, just call `stage.loadFile` multiple times. If you need to superimpose them then see the example:

http://nglviewer.org/ngl/?script=component/structure-superpose
(Source code here: https://github.com/nglviewer/ngl/blob/master/examples/scripts/component/structure-superpose.js)


There's no built in sequence viewer, but the COSMIC-3D website uses NGL to do something a bit like what you're after, e.g. load this page, scroll down to the mutations view and click a mutation to see the effect on structure
https://cancer.sanger.ac.uk/cosmic3d/protein/BRAF?pdb=4MBJ
