### ISSUE TITLE
Orthographic mode broken

### ISSUE THREAD

**Issue by fredludlow** [nglviewer/ngl#779]
Something seems to have broken orthographic camera mode recently - the easiest way to see this is to add a label representation and switch between perspective and orthographic. Orthographic seems to be viewed from behind (labels are upside down) and the rotation works "backwards" - objects that should be behind are displayed in front

@garyo - is it possible this is to do with the camera changes you made? I had a quick dig but can't see anything obvious. The compiled shader code has a line:

`geometry.viewDir = ( isOrthographic ) ? vec3( 0, 0, 1 ) : normalize( vViewPosition );`

Checking camera position it's still at negative z so that part looks okay, but somehow the scene is inside out, or with z flipped or something...

**Comment by garyo** [comment]
Thanks -- I'll check into it. Certainly possible my recent changes affected it.
