### ISSUE TITLE
About the interaction between molecules

### ISSUE THREAD

**Issue by J-DuYa** [nglviewer/ngl#784]
About the interaction between molecules

Description
I want to know if I can do intermolecular interaction through this plugin.？

Relevant Context
I want to click on a certain molecular structure, and then the interface will initially show the schematic diagram of the related molecular action in this area
If possible, can I achieve Schrödinger’s intermolecular effect through NGLViewer?

**Comment by fredludlow** [comment]
You can use the contacts representation to see the interactions in 3D (see the demo here: http://nglviewer.org/ngl/?script=representation/contact script here: https://github.com/nglviewer/ngl/blob/master/examples/scripts/representation/contact.js).

If your protein and ligand are separate files you first need to concatenate them (there's another demo here: 
http://nglviewer.org/ngl/?script=test/concat
script here: https://github.com/nglviewer/ngl/blob/master/examples/scripts/test/concat.js)

If you mean a 2D schematic then no, I'm not aware of anything like that right now, though maybe see the discussion in #782

**Comment by J-DuYa** [comment]
Thanks, i have other question.

if i want to measuring distance, angle, dihedral angle， is there such an api?

**Comment by fredludlow** [comment]
Yup, there are 3 representation types (distance, angle, dihedral), e.g.:
http://nglviewer.org/ngl/?script=representation/distance (source: https://github.com/nglviewer/ngl/blob/master/examples/scripts/representation/distance.js).
(replace distance with angle or dihedral in those URLs for the others)

You can also add with the mouse: Right-click pick atom1, then atom2, then atom2 again for a distance. Pick 3 atoms (repeat last one) for an angle, or 4 atoms (repeat last one) for a dihedral.

**Comment by J-DuYa** [comment]
Okay, i know. Thanks man.

**Comment by J-DuYa** [comment]
I ask a simple question how can i get the atom‘s infomation?

**Comment by J-DuYa** [comment]
What if I want to replace, copy and paste the molecular structure? Can it be achieved

**Comment by fredludlow** [comment]
You can dispose a component and load a new one. Editing coordinates and other atomic attributes generally works, but changing connectivity, adding/deleting atoms etc. isn't supported.

**Comment by fredludlow** [comment]
Closing - please re-open if you have other questions.
