### ISSUE TITLE
Issue building ngl

### ISSUE THREAD

**Issue by giagitom** [nglviewer/ngl#786]
I am encountering multiple issues like this one while trying to build

**Argument of type** ... **is not assignable to parameter of type 'Partial**

Any suggestion on how to solve?

```
error TS2345: Argument of type '{ clipNear: number; clipRadius: number; clipCenter: Vector3; flatShaded: boolean; flatColor: boolean; select: boolean; selectColor: boolean; opacity: number; depthWrite: boolean; ... 10 more ...; disablePicking: boolean; } & { ...; }' is not assignable to parameter of type 'Partial<{ linewidth: number; } & { opaqueBack: boolean; side: BufferSide; opacity: number; depthWrite: boolean; clipNear: number; clipRadius: number; clipCenter: Vector3; ... 16 more ...; background: boolean; }> | undefined'.
  Type '{ clipNear: number; clipRadius: number; clipCenter: Vector3; flatShaded: boolean; flatColor: boolean; select: boolean; selectColor: boolean; opacity: number; depthWrite: boolean; ... 10 more ...; disablePicking: boolean; } & { ...; }' is not assignable to type 'Partial<{ linewidth: number; } & { opaqueBack: boolean; side: BufferSide; opacity: number; depthWrite: boolean; clipNear: number; clipRadius: number; clipCenter: Vector3; flatShaded: boolean; ... 15 more ...; background: boolean; }>'.

154       } as WideLineBufferData), this.getBufferParams({
                                    ~~~~~~~~~~~~~~~~~~~~~~
155         linewidth: this.linewidth,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
157         opacity: this.lineOpacity
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
158       }))
```

**Comment by fredludlow** [comment]
I get a lot of things like this when changing dependency versions (e.g. TS, three etc.) - I suspect as a result of us not precisely enough specifying the versions in package.json. Are these errors present for you in a clean checkout of master? This is working for me now (just checked on Centos7 with node 12)

```
mkdir ngl-test
cd ngl-test
git clone https://github.com/nglviewer/ngl.git . --depth=1
npm ci
npm run build
```

The npm ci command checks package.json and package-lock.json are compatible and installs the exact set of modules specified in package-lock.json, as opposed to the normal npm install behaviour which will update package-lock.json (I think..., maybe check the docs on that one :) )

**Comment by giagitom** [comment]
Thanks for the hint @fredludlow when I use npm ci a lot of warnings desappear. However this seems not to be the issue.

If i try to build the clean master checkout it works without problems. But I need to incorporate my changes. Then I try to to do a rebase. During the rebase process there are two confilcts in  dist/ngl.esm.js and dist/ngl.js files. No problems in src/ . 

At the building phase I keep having the same errors (even using npm ci)

Could it be a problem due to the modules update? 

This is the first time I'm doing this, maybe I am doing something wrong.. But have no clue on what to do in this situation.

**Comment by giagitom** [comment]
Solved! Was a property declaration with the wrong type previously silent..
 I noticed that even with the clean master install during the build I get this
```
(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
chroma-js (guessing 'chroma')
signals (guessing 'signalsWrapper')
sprintf-js (guessing 'sprintfJs')
promise-polyfill (guessing '_Promise')

```
Is this normal?

**Comment by garyo** [comment]
`dist` is checked in although it is a build product. When merging or rebasing locally, just ignore that side and take yours.

**Comment by fredludlow** [comment]
Glad you found a fix @giagitom - is it something that needs fixing in the main NGL code?

I also get those missing global variable names, I had a brief look and it looked like a bit of a rabbit hole so I ignored them, but would be good to not have the warnings if anyone has any ideas!

**Comment by giagitom** [comment]
> Glad you found a fix @giagitom - is it something that needs fixing in the main NGL code?

Nothing from NGL side @fredludlow
