### ISSUE TITLE
Loading of local file

### ISSUE THREAD

**Issue by hoba87** [nglviewer/ngl#787]
I don't know if this can be solved within ngl, but loading of local files (here "ngl.pdb") when opening a local html file is not allowed at least on firefox. 
Here is my example html file:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
</head>
<body style="background-color:grey; margin:0; padding:0; overflow:hidden">
  <script src="ngl.js"></script>
  <script>    
    document.addEventListener("DOMContentLoaded", function () {
      var stage = new NGL.Stage("viewport");
      stage.loadFile("ngl.pdb").then(function(o) {
        o.addRepresentation("spacefill", {
          side: "front", sphereDetail: 0, radiusType: "covalent", scale: 0.5, colorScheme: "element",
        });
      });
      stage.setParameters({cameraType: "orthographic"});
    });
  </script>
  <div id="viewport" style="width:800px; height:600px;">
  </div>
</body>
</html>
```

**Comment by fredludlow** [comment]
This is a browser security policy (scripts contained in a local HTML file shouldn't be allowed to just open arbitrary other files from the filesystem).

Your best bet for testing is to run a lightweight server. Node and python both have good options:
https://www.npmjs.com/package/http-server
https://docs.python.org/3/library/http.server.html

e.g. if you HTML file is in /home/username/ngl/mypage.html (and assuming python 3)

```bash
cd /home/username/ngl
python -m http.server 8000
```
Then open:
http://localhost:8000/mypage.html in your browser

**Comment by hoba87** [comment]
Thanks, that works!
