### ISSUE TITLE
Coordinate systems inconsistencies

### ISSUE THREAD

**Issue by hoba87** [nglviewer/ngl#788]
I have observed some inconsistencies/bugs regarding the coordinate system, when combining a structure loaded from file and a shape. Three subissues I have observed:
* the viewed position of the shape object / shapeComp representation, already for (0,0,0), depends on the rotation angle (changing it simultaneously). 
* it seems that the minimum of the given shape coordinates are mapped to (0,0,0) or something different of the structure loaded from the file
* there is some issue with at least the z axis direction, it seems that the direction of the z-axis is opposed to the structure loaded from file

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
</head>
<body style="background-color:grey; margin:0; padding:0; overflow:hidden">
  <script src="ngl.js"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      var stage = new NGL.Stage("viewport");
      stage.loadFile("ngl.pdb").then(function(o) {
        o.addRepresentation("spacefill", {
          side: "front", sphereDetail: 0, radiusType: "covalent", scale: 0.5, colorScheme: "element",
        });
        o.autoView();
        o.setScale(1);
        o.setRotation([-1.5707963267948966,0,-1.5707963267948966]);
        o.setPosition([0,0,0]);
      });

      var shape = new NGL.Shape("shape");
      shape.addMesh(
        [ 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2 ],
        [ 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0 ],
        undefined, undefined, "surface"
      );
      var shapeComp = stage.addComponentFromObject(shape);
      shapeComp.addRepresentation("buffer");
      shapeComp.setScale(1);
      shapeComp.setRotation([-1.5707963267948966,0,-1.5707963267948966]);
      shapeComp.setPosition([0,0,0]);

      stage.setParameters({cameraType: "orthographic"});
    });
  </script>
  <div id="viewport" style="width:800px; height:600px;">
  </div>
</body>
</html>

```

**Comment by fredludlow** [comment]
I'm finding this a bit hard to reproduce (though you may well be right). Can you provide an example with the behaviour you'd expect and what you actually see?

(My understanding is that setPosition allows you to specify an offset (so setPosition([0,0,0]) would be a no-op unless you'd previously set it to something else)

**Comment by hoba87** [comment]
Ok, during preparation I found already (one/the) cause of the issues, I used the file ngl.pdb and the corresponding html file:
```
MODEL     1
ATOM      0   Si MOL     1      1.0   1.0   1.0   1.00  0.00          SI
ATOM      1   Si MOL     1      30.0  1.0   1.0   1.00  0.00          SI
ATOM      1   Si MOL     1      25.0  30.0  1.0   1.00  0.00          SI
ATOM      1   Si MOL     1      20.0  20.0  20.0  1.00  0.00          SI
ENDMDL
```
```
</head>
<body style="background-color:grey; margin:0; padding:0; overflow:hidden">
  <script src="ngl.js"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      var stage = new NGL.Stage("viewport");
      stage.loadFile("ngl.pdb").then(function(o) {
        o.addRepresentation("spacefill", {
          side: "front", sphereDetail: 0, radiusType: "covalent", scale: 0.5, colorScheme: "element",
        });
        o.autoView();
        o.setScale(1);
        o.setRotation([0,0,0]);
        o.setPosition([0,0,0]);
      });

      stage.setParameters({cameraType: "orthographic"});
    });
  </script>
  <div id="viewport" style="width:800px; height:600px;">
  </div>
</body>
</html>
```
![grafik](https://user-images.githubusercontent.com/6099617/93451537-9b934b00-f8d7-11ea-9a3f-79ef88acb042.png)


Just changing the rotation to "o.setRotation([-1.5707963267948966,0,0]);" I get this:
![grafik](https://user-images.githubusercontent.com/6099617/93451742-dac19c00-f8d7-11ea-8daf-a5dc7fca81e3.png)

Regarding the coordinates I would not expect all atom in one line.
However, when I change the ngl.pdb to 
```
MODEL     1
ATOM      0   Si MOL     1.0      1.0   1.0   1.0   1.00  0.00          SI
ATOM      1   Si MOL     1.0      30.0  1.0   1.0   1.00  0.00          SI
ATOM      1   Si MOL     1.0      25.0  30.0  1.0   1.00  0.00          SI
ATOM      1   Si MOL     1.0      20.0  20.0  20.0  1.00  0.00          SI
ENDMDL
```
I get what I expect:
![grafik](https://user-images.githubusercontent.com/6099617/93452684-fda08000-f8d8-11ea-9b9f-4806ad85b259.png)

So it seems, that ngl is misinterpreting floats when given as integers in the file.

**Comment by hoba87** [comment]
When adding a shape to the html file with these lines:
```
      var shape = new NGL.Shape("shape");
      shape.addMesh(
        [0, 0, 10, 10, 0, 10, 0, 10, 10, 10, 0, 10, 0, 10, 10, 10, 10, 20],
        [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
        undefined, undefined, "surface"
      );
      var shapeComp = stage.addComponentFromObject(shape);
      shapeComp.addRepresentation("buffer");
      shapeComp.setScale(1);
      shapeComp.setRotation([0,0,0]);
      shapeComp.setPosition([0,0,0]);
```
I got this (rotation set to 0 for both):
![grafik](https://user-images.githubusercontent.com/6099617/93454460-5709ae80-f8db-11ea-9912-2fc39a358223.png)

rotating by 90° (with the mouse):
![grafik](https://user-images.githubusercontent.com/6099617/93454922-f038c500-f8db-11ea-8172-2b85930d6665.png)

by setting o.setRotation([-1.5707963267948966,0,0]); and shapeComp.setRotation([-1.5707963267948966,0,0]);
![grafik](https://user-images.githubusercontent.com/6099617/93454778-b8ca1880-f8db-11ea-8506-7c2b0b8a9da1.png)

Regarding the coordinates I would expect the same as for the image rotated with the mouse.

**Comment by hoba87** [comment]
With the last case with o.setRotation([-1.5707963267948966,0,0]); and shapeComp.setRotation([-1.5707963267948966,0,0]);
and changing the y!-coordinate (either that should be z or it should make a difference if doing it before or after the rotation) with shapeComp.setPosition([0,15,0]);
the result looks like I would have expected without setting the position
![grafik](https://user-images.githubusercontent.com/6099617/93456104-87524c80-f8dd-11ea-9585-122d7c0c595d.png)

while rotated back by mouse it looks like
![grafik](https://user-images.githubusercontent.com/6099617/93456700-59213c80-f8de-11ea-9254-5d4d252779e0.png)

and with shapeComp.setPosition([0,0,0]); and rotated back by mouse
![grafik](https://user-images.githubusercontent.com/6099617/93456808-7a822880-f8de-11ea-8626-5955768413a7.png)

**Comment by fredludlow** [comment]
I think the issue is with these PDB files. The spec is a fixed-width format, not a delimited format, so your numbers don't necessarily fall in the right columns:
http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM

A useful way to check is to add a label representation with: labelType: 'format' and labelFormat: '%(x)d, %(y)d, %(z)d' - this will display x,y,z coords next to each atom:

```javascript
o.addRepresentation("label", {
  labelType: 'format', labelFormat: '%(x)d, %(y)d, %(z)d'
});
```

The first file you pasted is being parsed with all z at 0.0 (hence them lining up when you rotate it).

You can use the pqr format if you want a delimited format that's easier to hack by hand (see example input in the data directory).

If you're still having problems with the rotation etc after fixing the files then let me know.

**Comment by hoba87** [comment]
Ok, if I align the file according to the format specified, the atomic coordinates are fine. I've written the pdb file with the ase package, so I will open an issue there.
However, the problems with the shape are still present.

**Comment by fredludlow** [comment]
So I'd never really played with setRotation(Array[3]) before - the rotation is around the centre of the object (as opposed to the mouse rotation which is rotating the whole scene).

You can use the `setTransform` method on a component to do something like what you want, see this example:
https://codepen.io/fludlow/pen/eYZxNVL

`setTransform` takes a `Matrix4`, but you can build one from Euler rotations in a roundabout way:

(These are three.js types, but exported by NGL
```javascript
var e = new NGL.Euler(-Math.PI / 2, 0, 0)
var m = new NGL.Matrix4()
m.makeRotationFromEuler(e)

comp.setTransform(m)
```

**Comment by hoba87** [comment]
Thanks, that works now as expected. I have added a hint in the documentation of setRotation with the pull request.
