### ISSUE TITLE
Is it possible to change the min/max values of color='bfactor'?

### ISSUE THREAD

**Issue by hainm** [nglviewer/ngl#790]
Hi, 

This is the original question by @sperezconesa in [nglview](https://github.com/nglviewer/nglview/issues/785#issuecomment-685922616). 

> Hello,
> Is it possible to change the min/max values of color='bfactor'? I would like to have to different representations that share bfactor and min/max scales.
> Thank you very much and keep up the good work!
> Best,
> Sergio

> > hi @sperezconesa I am not sure if you can directly achieve that. Please see the custom color here if that can help: #839
> 
> Is there any chance this could become a new feature? Including a flag like `color_scale_min=0.2,color_scale_max=0.5` for the representations. I was excited to add the structures of this figure to our new mdsrv server:
> ![image](https://user-images.githubusercontent.com/27727343/93573408-62221480-f997-11ea-8951-7ef831713788.png)
> But I can't have the lipids and protein share the same colorscale min and max values since they are automatically set up. By the way if anyone is interested the article can be found [here](https://www.biorxiv.org/content/10.1101/2020.07.06.187484v1.abstract)

Do you all have any idea? Thanks.

**Comment by sperezconesa** [comment]
Thank you very much for considering this!

**Comment by fredludlow** [comment]
The `colorDomain` parameter should do what you want:

e.g. https://codepen.io/fludlow/pen/oNxQKoQ

**Comment by sperezconesa** [comment]
Awesome! I wonder how I didn't see this. Maybe it is a bit hidden in the documentation. Now I have what I needed.

**Comment by hainm** [comment]
thanks @fredludlow.
