### ISSUE TITLE
 How can I get the content of my sample file through NGL？

### ISSUE THREAD

**Issue by J-DuYa** [nglviewer/ngl#794]
How can I get the content of my sample file through NGL

**Comment by fredludlow** [comment]
The original file isn't saved anywhere. You can make a fetch /ajax request from your own code (which will, in practice, be fast as it hits the browser cache unless you do something to prevent that).

You can also do the fetch in your code and pass the file data in to ngl as a Blob (there's an example of this here https://github.com/nglviewer/ngl/blob/e8713514cfa7100a8313b3ff34a3c94b4125ced4/examples/parallel.html)

**Comment by J-DuYa** [comment]
If I modify the molecular structure in the interface, can I get the modified file information

**Comment by J-DuYa** [comment]
https://www.rcsb.org/3d-view/6V94?preset=ligandInteraction&sele=GNP


Is this page's download an internal method of NGL?

**Comment by fredludlow** [comment]
That link takes me to a molstar view? Are you actually modifying the structure? If so, you can download it as a PDB file. `new NGL.PdbWriter(structure).getString()`.

**Comment by J-DuYa** [comment]
> That link takes me to a molstar view? Are you actually modifying the structure? If so, you can download it as a PDB file. `new NGL.PdbWriter(structure).getString()`.

This function can be downloaded, but it is not the same as what I expected. I will take a look at it then, thanks.

**Comment by J-DuYa** [comment]
Then I can take the liberty to ask, can I get the file information after the change (delete operation) on the page? If there is no similar method, what is the reason?

**Comment by fredludlow** [comment]
Sorry, I think we're talking at cross purposes a bit :)

NGL doesn't currently have any way to: 
1) Edit molecules in a general way and save the results
  + You can set a selection which filters which atoms get drawn, but they're still in the internal representation and if you use `PdbWriter` you'll still have all the atoms
  + You can also change atomic coordinates/properties etc (e.g. to change the x coordinate of the first atom in the first structure: `var s = stage.compList[0].structure; var ap = s.getAtomProxy(); ap.index=1; ap.x = 101.0`). Changes you make like this will appear in the `PdbWriter` output (but the number of atoms in
   + The reason for not supporting this is that it's out of the scope of a viewer - there's a lot of cheminformatics, protein modelling, DNA modelling etc you'd need to code up or bring in from somewhere to enable this - being able to save updated coords/bfactors etc was easy to implement, but general bonding changes etc would require putting much more chemical knowledge into NGL.

2) You load 3 molecules, setup representations, then remove a molecule and other representations and want to save a "view" (the current state of the stage). 
  + This is also not built in, but you can achieve this in various ways. 
    + A quick way is to iterate through `stage.compList`, then for each component, note e.g. `component.structure.path`, and `component.getParameters()`, iterate through `component.reprList` and record representation types plus `repr.getParameters()` - then write a function that reads this data and applies the state to stage. This isn't totally reliable as components might be generated directly using e.g. the `Shape` api, but for simple "load a moleclue from a file and apply representations" it'll work.
  + Why this isn't built in you'd have to ask Alex, I would hazard a guess that in the early days (5+ years ago) it wasn't as high priority as other concerns (e.g. performance, features etc).
