### ISSUE TITLE
structure hierarchy and secondary structure not recognized from NGL loading a pymol generated cif file 

### ISSUE THREAD

**Issue by giagitom** [nglviewer/ngl#798]
Hi,
This file as an example. NGL can't retrieve secondary structure information from it. 
[test.cif.txt](https://github.com/nglviewer/ngl/files/5291636/test.cif.txt)

**Comment by DustBytes** [comment]
Chimera failed to load this file.
It seems file format has issues.

**Comment by fredludlow** [comment]
@giagitom - do we think pymol gets it wrong, or that both chimera and NGL do? (i.e. should I close this ;)?)

**Comment by giagitom** [comment]
No problem for me this can be closed. Seems that it is also difficult to import chimera generated cif #809 though :)
