### ISSUE TITLE
GRO files with molecules defined by 3 letters don't load

### ISSUE THREAD

**Issue by ixdi** [nglviewer/ngl#804]
Hi,

I supose there's a bug. If I load a water molecule as a GRO file with a content like

```
Generated by gmx solvate
16
    1WAT     OW    1   1.736   0.839   0.257
    1WAT    HW1    2   1.777   0.781   0.322
    1WAT    HW2    3   1.643   0.831   0.274
    1WAT     MW    4   1.730   0.831   0.267
    2WAT     OW    5   1.602   0.771   1.252
    2WAT    HW1    6   1.557   0.838   1.303
    2WAT    HW2    7   1.690   0.807   1.238
    2WAT     MW    8   1.608   0.784   1.256
    3WAT     OW    9   0.530   1.022   0.486
    3WAT    HW1   10   0.620   0.997   0.470
    3WAT    HW2   11   0.526   1.115   0.463
    3WAT     MW   12   0.542   1.031   0.481
    4WAT     OW   13   1.646   1.725   0.628
    4WAT    HW1   14   1.658   1.671   0.706
    4WAT    HW2   15   1.683   1.673   0.557
    4WAT     MW   16   1.652   1.710   0.629
   5.00000   5.00000   5.00000
```

NGL doesn't load the molecule

If I replace all the WAT for WATE then NGL loads it. I attach two files to test it.
[water.zip](https://github.com/nglviewer/ngl/files/5408771/water.zip)

There're molecules that are defined with only 3 letters.

Thanks

**Comment by giagitom** [comment]
Both work for me. I think WATE residue is treated like a ligand and shown in sticks with the default representation, instead WAT is not shown by default because it is recognized as a solvent.
