### ISSUE TITLE
How can I add a new colormaker

### ISSUE THREAD

**Issue by bralexander** [nglviewer/ngl#805]
I have a working CodePen that colors the residues based on machine learning probabilities from a CSV. I want to add this functionality as a colormaker available in examples.
I have extended colormaker similar to resname-colormaker.ts and colormakerRegistry.add the scheme. I also added the staging js file in the examples/scripts/color directory. 
When I click on the file in the webapp, I get a console message THREE.COLOR: unknown color 'compvis' (the scheme id I assigned)
I noticed that my colormaker is not included in the ngl.dev.js file, and it is also missing from the build directory when I open Sources in chrome dev tools. But when I look in the build directory locally, the files are there.
Can anyone help me understand what I am missing that is preventing me from accessing my colormaker scheme?

**Comment by fredludlow** [comment]
Rollup is possibly ignoring the file as it isn't imported anywhere? You
could try importing it from the top level src/ngl.ts (registering it as a
scheme is a side effect of import)

**Comment by bralexander** [comment]
Ah yes! Forgot about that 🤦‍♂️. Thanks! Now I just need to get the csv parser working.

**Comment by bralexander** [comment]
Got it working! I found out autoLoad in loader-utils can be used as a CSV parser -- made things a lot easier. Now I need to add some user input options to the html page, and make a coloring gradient. 
I also want to make a proxy for the CSV so when you hover over the residue it will tell you the probability, and what residue the neural net thinks should be there. I might have to ask a new question for that.
