### ISSUE TITLE
NPM install is broken

### ISSUE THREAD

**Issue by omaraltayyan** [nglviewer/ngl#806]
NPM installation is broken due to renaming of this repo most likely, version of @sgratzl/ngl works but regular NGL fails to install

**Comment by garyo** [comment]
Can you give more info about what's broken? The repo hasn't been renamed recently.

**Comment by omaraltayyan** [comment]
> Can you give more info about what's broken? The repo hasn't been renamed recently.

i am using node version 12, doing `npm install ngl` doesn't work

```
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path /app/node_modules/ngl
npm ERR! dest /app/node_modules/.ngl.DELETE
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, rename '/app/node_modules/ngl' -> '/app/node_modules/.ngl.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-26T21_59_13_939Z-debug.log
```

**Comment by garyo** [comment]
Hmm, that's weird. It's working for me. npm v6.14.8, Ubuntu 18.04.
```sh
% mkdir /tmp/app
% cd /tmp/app
% npm init
...
% npm install ngl
npm notice created a lockfile as package-lock.json. You should commit this file.

+ ngl@0.10.4
added 1 package from 1 contributor and audited 1 package in 1.206s
found 0 vulnerabilities

% ls
node_modules/  package-lock.json  package.json
```

**Comment by omaraltayyan** [comment]
> Hmm, that's weird. It's working for me. node v12.19.0, npm v6.14.8, Ubuntu 18.04.
> 
> ```shell
> % mkdir /tmp/app
> % cd /tmp/app
> % npm init
> ...
> % npm install ngl
> npm notice created a lockfile as package-lock.json. You should commit this file.
> 
> + ngl@0.10.4
> added 1 package from 1 contributor and audited 1 package in 1.206s
> found 0 vulnerabilities
> 
> % ls
> node_modules/  package-lock.json  package.json
> ```

ok so it's either some package i have that conflicts with ngl somehow or corrupts the setup, or some bug in the npm version i have, i am using 12.18.4.

to be honest we have more than 2000 NPM packages in total so it's not a strange thing to have such issue.

i'll install the latest version of NPM `12.9`, then i'll install the package on it's own to see if it's a conflict issue of sorts

**Comment by garyo** [comment]
Closing; feel free to reopen if needed.
