### ISSUE TITLE
get Amino Acid Index numbers

### ISSUE THREAD

**Issue by nvelden** [nglviewer/ngl#818]
I can get the AA sequence using:

`var aa = o.structure.getSequence()`

Is there also a way to get the positions (index numbers)?

**Comment by fredludlow** [comment]
Yes, something like the getSequence implementation (https://github.com/nglviewer/ngl/blob/master/src/structure/structure.ts#L1019)

```
var seq = []
o.structure.eachResidue( rp => {
  var code = rp.getResname1() // The single-letter code, use `rp.resname` for 3-letter
  if (code !== 'X') { seq.push(code)}
})
```

The eachResidue function also takes a selection as a second argument, in case you want to limit to a chain.

Caveat: I've not tested to see how this would behave if your input file doesn't have the residues in the right order.

**Comment by fredludlow** [comment]
Sorry, I forgot the critical part about getting the numbering! The ResidueProxy `rp` in the example below gives you access to 
`resno` (residue number from the file) as well as a bunch of other properties and methods:  http://nglviewer.org/ngl/api/classes/residueproxy.html

```javascript
var seq = [] // Populated with [ ['A', 1], ['C', 2], ...]
o.structure.eachResidue( rp => {
  var code = rp.getResname1() // The single-letter code, use `rp.resname` for 3-letter
  if (code !== 'X') { seq.push([code, rp.resno])}
})
```

**Comment by nvelden** [comment]
Fantastic! Thanks a lot.

**Comment by nvelden** [comment]
I can't seem to find it among the residueproxy properties but if I for instance have a protein complex like:

https://www.rcsb.org/3d-view/6XKX/1

is there a way to find out per residue to which subunit an amino acid belongs?

**Comment by ppillot** [comment]
Depending on your definition of "subunit", the properties `chainname` or `chainid` of residue proxy could return an indication. You might also be interested in the `entity` property.

**Comment by nvelden** [comment]
thanks! I could select the different sub-units using chainname
