### ISSUE TITLE
dispose representation by name

### ISSUE THREAD

**Issue by nvelden** [nglviewer/ngl#827]
based on the NGL example:

https://codepen.io/pen?&editors=001

```
stage.loadFile("data://1blu.mmtf").then(function (o) {
  o.addRepresentation("ball+stick", { 
color: "red",
name: "sel1"})
   o.autoView()
})
```

How can I remove the representation by its name `sel1`?

I tried: 

`stage.getRepresentationsByName('sel1').dispose()`

`stage.removeRepresentation('sel1')`

`stage.getRepresentationsByName('sel1').removeRepresentation()`

`stage.disposeRepresentation('sel1')`

But none are working

**Comment by fredludlow** [comment]
`stage.getRepresentationsByName` returns an `RepresentationCollection` http://nglviewer.org/ngl/api/classes/stage.html#getrepresentationsbyname, so I think the full version would be:

`stage.getRepresentationsByName('sel1').list[0].dispose()`

If the name matches multiple representations you can dispose all of them like this
`stage.getRepresentationsByName('sel1').list.forEach(r => r.dispose())`
