### ISSUE TITLE
"o.addRepresentation('surface' " has a bug with cube format files

### ISSUE THREAD

**Issue by dou-du** [nglviewer/ngl#829]
I am developing a custom JupyterLab extension to visualizer cube format file. There is a problem when using
the "o.addRepresentation('surface' " with cube format files. It gives error as:

**Uncaught SyntaxError: Function statements require a function name**

This problem is only for cube format file. If I use other format file to create 'surface', it will not cause
any error. Could you give any suggest which function could lead to this error ? Thanks.

**Comment by fredludlow** [comment]
HI @dou-du, do you have an example file and steps to reproduce?

**Comment by dou-du** [comment]
> HI @dou-du, do you have an example file and steps to reproduce?

Thanks @fredludlow . I have already figured out the problem. It is a function in the marching-cube.ts, which has not defined the return type. This leads to the webpack convert it to a function without function name. I made a pull request to fix it. #836
