### ISSUE TITLE
Angular installation

### ISSUE THREAD

**Issue by LuisCastilloV98** [nglviewer/ngl#842]
Hello,

Do you have any tutorial on how to install it in angular? I've tried anyway but it always tells me that the NGL variable is undefined.

Best regards

**Comment by harryjubb** [comment]
Hi Luis, is this Angular 1 or 2+?

I haven't tried NGL with any version of Angular, but if you're using Typescript and / or ES6+ imports, you should be able to import the NGL `Stage` object from the ESM build:

```typescript
import { Stage } from './ngl/ngl.esm';
```

In this case I had built NGL separately, by cloning the repository and running the `npm run build-min` script: then copied the `dist/ngl.esm.js` file to `./ngl/ngl.esm.js` in my local repository.

It may be possible to import the ESM build from the NPM package, but I'm not sure on which versions of the NPM package support that without further testing (@fredludlow may know).

If you want TypeScript typing as well, you'll also need to import some types from the TS declarations from `declarations/ngl.d.ts` (can be built locally with `npm run dts`)

Another option would be to include the built NGL JS (`dist/ngl.js`) in a `script` tag, which gives you a global `NGL` object (but no TS support for NGL). If you're using Angular 2+ with TypeScript, you'll probably need to tell TS that the global `NGL` variable exists with:

```typescript
declare var NGL: any;
```

**Comment by LuisCastilloV98** [comment]
Thanks
