### ISSUE TITLE
setRepresentation function

### ISSUE THREAD

**Issue by gbayarri** [nglviewer/ngl#850]
Hi, I'm trying to change a representation type without doing removeRepresentation / addRepresentation and I don't get it.

This is my code:

```
const re = new RegExp('struc_')
for(const item of stage.getRepresentationsByName(re).list) {
  item.setRepresentation( 'cartoon' )
}
```
And that's the error I get:

Uncaught TypeError: Cannot read property 'count' of undefined
    at Counter.listen (ngl.esm.js?af5c:54257)
    at RepresentationElement.setRepresentation (ngl.esm.js?af5c:76173)

I assume that the problem is that I should pass a Representation object instead of a string, but I don't know hot to create a new Representation object with the new parameters. Neither any example.

Can anyone help me?

**Comment by garyo** [comment]
Removing and adding is the normal/supported way to do this. But if you want to update the representation of a `representationElement` (which is what `getRepresentationsByName` returns) you're right that you'll need to construct a representation. See for instance ballandstick-representation.ts; the constructor takes the structure, the viewer (`stage.viewer`) and your representation parameters. Untested, but you should be able to get the structure from an existing representation using `item.repr.structure`.
This will all get a bit easier when we ship the typescript decls in a future update.

**Comment by gbayarri** [comment]
Ok, thanks!
