### ISSUE TITLE
select chain with blank or undefined chain identifier?

### ISSUE THREAD

**Issue by colin-combe** [nglviewer/ngl#857]
Hi,
I'm not familiar with the NGL selection syntax - some pdb files we work with end up with blank chain identifiers, is there a way to select these with the NGL selection syntax?
Something equivalent to this from the pymol selection docs - "_A blank or undefined chain identifier is entered as two apostrophes_".

best wishes,
Colin

**Comment by fredludlow** [comment]
The current behaviour is to automatically assign chain IDs where they're not supplied, so typically you can just use `:A`. This surprised me a bit when I looked at it earlier. The code will also try to detect breaks in the chain and start a new chain ID when this happens, which could lead to unpredictable chain identifiers.

Do you have structures that are a mixture of atoms with standard chain identifiers and blank ones? If it's a mixture then that's tricky, but there's a possible solution*. If they're exclusively one or the other then for the blank ones a blank chain selection term doesn't actually add anything (it would be all of your atoms)

* Would need a bit of thought but possible:
1. A supress automatic chainname assignment
2. Add code to handle `:` or maybe `:\0`?!  and treat that as matching undefined/null/" "

**Comment by colin-combe** [comment]
thanks fred,
it is a mixture of standard chain ids and blank ones, so it is the tricky case.

I'm not sure it is doing automatic chainname assignment when its a mix of blank and not blank ids, I still see the blank ids when using the 'chain proxy' object returned by structure.getChainProxy()

**Comment by fredludlow** [comment]
Are you able to share an example file? (I can just strip some chain IDs from a PDB if not but if you can share a real file it would save any misunderstanding on my part :) )

**Comment by colin-combe** [comment]
> Are you able to share an example file?

I would need to check with the person whose file it is.

Also, I'm about to be Away From Keyboard for three weeks - I will pick up this problem again when I'm back and share an example file.

Thanks for your responses,
cheers,
C

**Comment by fredludlow** [comment]
Okay - I had a quick play, and this patch in selection-parser.ts fixes it **if the first atom has a chain ID** (but not if you start without chain IDs and have them later). As you say, let's pick it up in a few weeks.

selection-parser.ts about L410
```javascript
    const chain = atomname[0].split(':')
    if (chain.length > 1) {
      if (chain[1]) {
        sele.rules!.push({
          chainname: chain[1]
        })
      } else { 
        sele.rules!.push({
          chainname: ""
        })
      }
    }
```

**Comment by colin-combe** [comment]
hi Fred, 
the first atom does have a chain ID so i can test your workaround,
um... I'm not sure how to get the built ngl.js file (i think it is an older one in the dist directory of your WIP branch),
I do `npm install ngl` (?) then get the .js file from where?
cheers,
Colin

**Comment by colin-combe** [comment]
sorry... I didn't see the file DEVELOPMENT.md with the build instructions in it

**Comment by colin-combe** [comment]
yes, I think your workaround works. I see from your commit comment that there would still be work to do making this consistent before the changes could be merged into the main branch.   

I think the pdb files come from https://salilab.org/modeller/, here's an example: 
[test_mischain.pdb.txt](https://github.com/nglviewer/ngl/files/6396498/test_mischain.pdb.txt)

thanks for your help,
Colin

**Comment by colin-combe** [comment]
the software that produced these files no longer gives blank chain identifiers,
i think this can be forgotten about
