### ISSUE TITLE
Undo superpose?

### ISSUE THREAD

**Issue by gbayarri** [nglviewer/ngl#863]
Hi, Is it possible to undo a superposition? I'm not sure if I'm following the correct steps:

1. Get original center of components
```
const c1_pos = c1.getCenter()
const c2_pos = c2.getCenter()
```

2. Superpose structures
```
const s1 = c1.structure
const s2 = c2.structure
NGL.superpose(s1, s2, true, ":B", ":B")
c1.updateRepresentations({ position: true })
```

3. After 2 seconds, try to move the two components again to the initial positions
```
setTimeout(() => {
  c1.setPosition(c1_pos)
  c2.setPosition(c2_pos)
  c1.autoView()
}, 2000)

```

The 3rd step moves again the two components, but not to the initial position. Doing console.log() of c1.getCenter() / c2.getCenter() after each step gives different positions, so either I'm getting the position in the wrong way or I'm setting it badly. Or both ;)

**Comment by fredludlow** [comment]
You can superimpose in two ways:
1. Actually alter x,y,z coordinates of the atoms and rebuild (NGL.superpose and NGL.Superposition do this, with some book-keeping for things like assemblies/symmetry)
2. Get the transformation matrix (you can use NGL.Superposition to get the matrix) and set the matrix on the structure e.g. `c2.setTransform(someMatrix)`. Internally x,y,z for each atom stays the same, the transform is done as a final step (on the GPU I think)

The second way is trivially reversible, you just set the Transform back to the identity matrix:
```javascript

Promise.all([
  stage.loadFile('data://sp-ido40.mol2').then(function (o) {
    o.addRepresentation('ball+stick')
    return o
  }),

  stage.loadFile('data://sp-after.mol2').then(function (o) {
    o.addRepresentation('licorice')
    return o
  })
]).then(function (ol) {
  // Create Superposition object but don't actually do the transform
  var sp = new NGL.Superposition(ol[0].structure, ol[1].structure)
  console.log(sp)
  // set the transformation matrix on the component:
  ol[0].setTransform(sp.transformationMatrix)
  ol[1].autoView()

  setTimeout(() => {
    // Restore
    ol[0].setTransform(new NGL.Matrix4())
  },
  2000)
})```


Undoing the first method (where you've actually edited x,y,z) is harder as the code currently stands (there's no exposed "transform this structure by this matrix" function), and there's an issue that with repeated doing/undoing you'd lose some precision in the coordinates. If this is really what you want to do you/we we could refactor align-utils.ts and superpose.ts to expose the appropriate function

**Comment by gbayarri** [comment]
Thanks @fredludlow , but the second way doesn't allow to perform sequence alignment and pass selections.

Is this code actually doing a superposition? Taking as a example the two structures of the gallery, they don't superpose:

https://codepen.io/gbayarri/pen/zYZYPXX

**Comment by fredludlow** [comment]
Yeah, the API isn't as nice, but you can do:

```javascript
var sp = new NGL.Superposition(
  ol[0].structure.getView(new NGL.Selection(':B'),
  ol[1].structure.getView(new NGL.Selection('')
)
```
(Superposition takes a `StructureView`)

Updated example here is superimposing
https://codepen.io/fludlow/pen/bGqGMwM?editors=1011

**Comment by gbayarri** [comment]
Ok, that will do the trick. 

Thanks!
