### ISSUE TITLE
Contact List

### ISSUE THREAD

**Issue by samuelmurail** [nglviewer/ngl#867]
Hi,

First of all great work !I
I want to list all contact (Hydrogen bonds, ...) from a contact representation. This is referring to issue #782. I have added a comment, but this is not reopening the issue, sorry if I did wrong.

I am not familiar with js, I am wondering is it possible to use the `getContactData()` function with something like the NGL@2.0.0-dev.32 - interactive/ligand-viewer from the gallery.

Here is what I tried :
```
$ contactRepr.repr.getContactData()
```
But i have an error `"t is undefined"`

So I tried :
```
contactRepr.repr.bufferList[0].picking.contacts.contactStore
```
I have access to interaction type and indexes of atoms, but I don't know how to link the indexes to the structure indexes, to get for each contact the atom names and residues involved.
Thanks. Samuel

**Comment by fredludlow** [comment]
Long overdue reply for historical reference:

```javascript
stage.loadFile("rcsb://1ajx").then(c => {
  var reprElement = c.addRepresentation('contact')
  console.log(reprElement.repr.getContactData(c.structure)) 
})
```
