### ISSUE TITLE
HTTP vs HTTPS

### ISSUE THREAD

**Issue by appukuttan-shailesh** [nglviewer/ngl#873]
I am totally new to using `ngl`, and currently trying to port some old HTML content to a new website.
One of the resources that my page tries to access is:
mmtf.rcsb.org/v1.0/full/5J2X

I find that I get different behaviors during my testing vs on the main website.
To elaborate:
at one place the call is made using HTTP:
http://mmtf.rcsb.org/v1.0/full/5J2X
while it uses HTTPS in the other case:
https://mmtf.rcsb.org/v1.0/full/5J2X

In the former case I am unable to load this resourse as I get the error:
>Mixed content: load all resources via HTTPS to improve the security of your site
All my web pages make use of HTTPS, and so it does not allow me to make the HTTP calls.
I am unsure how `ngl` decides which protocol employ: HTTP or HTTPS? What is this dependent on?

I load `ngl` on my page via:
<script src="https://unpkg.com/ngl"></script>

I realize I am providing very few details here, but that is partly because I am not well aware of what would be relevant info in this case. As I mentioned, I am very new to using `ngl`. Thanks for any help.

**Comment by fredludlow** [comment]
Rather late reply:

The unpkg.com version is pretty old - it's possible this is fixed in a more recent release? https://unpkg.com/ngl@2.0.0-dev.39/dist/ngl.umd.js

I'm assuming you're loading these with the rcsb scheme? i.e. "rcsb://5j2x" - It should detect whether your page is http or https and connect to rcsb.org with the same method

**Comment by appukuttan-shailesh** [comment]
Thanks for your reply. I was using the `rcsb://` scheme previously. After reading your post, it gave me the idea to explictly use the `https` link for the resource. And now everything works as expected. I realize that, in general, it is advisable to use the `rcsb://` scheme.
