### ISSUE TITLE
How can I get correct values of the global variables in this.atomColor function?

### ISSUE THREAD

**Issue by TsungMingYangNTUT** [nglviewer/ngl#874]
The version of NGL I used : `ngl-2.0.0-dev39`.

```javascript
// Record resno of hovered atom
var hoveredResno = null;

// NGL Stage
var stage = new NGL.Stage("viewer", { backgroundColor: 'white', tooltip: true });

// My color scheme
var mySchemeId = NGL.ColormakerRegistry.addScheme(function (params) {

    this.atomColor = function (atom) {
        // Default color : Gainsboro
        var color = 0xDCDCDC;

        // If the atom is hovered, color it red.
        // * but `hoveredResno` is always null.
        if (atom.resno == hoveredResno) {
            color = 0xFF0000;
        }

        // Return hex
        return color;
    };
});

stage.signals.hovered.add((pickingProxy) => {
    if (pickingProxy && pickingProxy.atom) {
        // Set hoveredResno
        hoveredResno = pickingProxy.atom.resno;
    }
});

// stage.loadFile(.....)
```
My problem is that : In `this.atomColor`, I can't get the new or correct value of the global variable `hoveredResno`, it is always `null`.

Is this problem related to `function context` ? 

Thank you.

**Comment by fredludlow** [comment]
Hmm, that looks okay to me, assuming this is copy/pasted then the scopes look fine - you're accessing hoveredResno which isn't declared in inner scopes so should look up the chain of enclosing scopes. What do you see if you set a breakpoint (or console.log) just after the line where you set hoveredResno?

**Comment by TsungMingYangNTUT** [comment]
I saw `hoveredResno` was set to  a new `atom.resno` (in `hovered` event).

```javascript
// Set hoveredResno
hoveredResno = pickingProxy.atom.resno;
console.log(hoveredResno); // a new resno.
```

**Comment by fredludlow** [comment]
Sorry - revisiting and just realised that atomColor is not re-evaluated on hover...

You will, for now at least, need to listen to hover events and update the colorScheme (or reset the selection on a representation). I've got a change in a private version which I will write up and make a PR for that should make this a lot easier 
 - it exposes a hook so that colormaker code can trigger a representation (color) update.
