### ISSUE TITLE
using pdbwriter.download  this.structure.eachModel is not a function

### ISSUE THREAD

**Issue by JohnMica** [nglviewer/ngl#875]
hi 
i am using Vue to play with NGL and i managed to load files and representations easily

NGL version  "2.0.0-dev.37",

now that i want to export as PDB it seems that there is a problem and i am not sure which way to solve it.

The main idea is to 
- Load 2 files
- export current view as PDB file
- no modifications done in the front-end

using the PdbWriter idea that i have found on  http://nglviewer.org/ngl/?script=showcase/ferredoxin gui.js line 1325 (    `var pdbWriter = new NGL.PdbWriter(component.structure)`)
 and the Issue closed about exporting PDB files [794](https://github.com/nglviewer/ngl/issues/794)

i am trying to do something similar 

```
// this.stage is the NGL stage inside the Vue Component
// mapping through the comList and getting the structures
// getData() is deprecated so not sure what to use anymore

   let structures = this.stage.compList.map(el => el.structure)
      let pdbWriter = new NGL.PdbWriter(structures)
      console.log(pdbWriter)
      pdbWriter.download('structure')
```
the error is that 
```
this.structure.eachModel is not a function

```

and i am at a loss

is this a bug  or something changed in the library ?

**Comment by fredludlow** [comment]
As written, it looks like you might be passing in an array of structures to the PdbWriter class, but it is expecting a single structure?

**Comment by JohnMica** [comment]
I am passing an array as the "current view" contains multiple files. 
I am not editing in the front-end any files (representations/components) just loading them. 

Is I pass the actual Stage to PdbWriter it still errors out.

**Comment by fredludlow** [comment]
The constructor for PdbWriter takes a single structure (it's not smart enough to merge a bunch of structures into one - in fact in almost all cases that probably wouldn't generate valid output if it did). So, you can write a PDB file for each structure and merge on the server (using something like biopython), or, you could try using concatStructures to merge the structure objects and then write - not sure how valid the output would be if you have repeated residue numbers etc...

**Comment by JohnMica** [comment]
Thanks for this. 

What I am trying to achieve is to simply "merge and download in the front-end only" the combined structures. 
I will try the concatStructure and see what happens but perhaps this "merge and download" could be something for future development?

**Comment by fredludlow** [comment]
I'm going to close this for now. It would be a nice addition but a thorough implementation seems out of scope (it should be possible in a quick way with concatStructure but getting the full nuance of the PDB format correct in the general case would require a much larger effort)
