### ISSUE TITLE
how to disable the browser scroll bar when using mouse wheel in ngl viewport

### ISSUE THREAD

**Issue by worldresize** [nglviewer/ngl#878]
when i want to use mousewheel in nglviewport,the browser scroll bar works together.

**Comment by fredludlow** [comment]
The simple way to disable mouse scrolling of the window is:

`window.addEventListener("wheel", e => e.preventDefault(), { passive:false })` 
(see [stackoverflow](https://stackoverflow.com/a/23606063/218572))

But depending on your page and the client device this can make it hard to navigate around the page. One solution would be:

```javascript
const stageContainer = document.getElementById('ngl-stage') // Whatever element you create the stage in
function maybeScroll(event) {
  if (stageContainer.contains(event.target)) {              // If wheel event occured within the viewer
    event.preventDefault();                                 // prevent the default (scrolling the page)
  } 
}
window.addEventListener('wheel', maybeScroll, {passive: false})
```

This is still problematic if your canvas fills the viewport as the user has to use the scrollbar or keyboard to move around.

**Comment by worldresize** [comment]
thank you very much, it works!

**Comment by ShangChien** [comment]
This is the official display [DEMO](http://nglviewer.org/ngl/gallery/)
```
// Handle window resizing
window.addEventListener( "resize", function( event ){
    stage.handleResize();
}, false );
```
Even though the above code has been added, the console still outputs the following red error：
```
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.
```
![image](https://user-images.githubusercontent.com/48350636/212448276-be45d6d1-a54e-40d7-965c-4b9d336cde63.png)

It is same error in my case, how to get rid of this error ?
Thank you!
