### ISSUE TITLE
Load PDB directly from AlphaFold Protein Structure Database

### ISSUE THREAD

**Issue by nvelden** [nglviewer/ngl#879]
With the exciting release of the AlphaFold protein structure database would it be possible to add the option to load PDB files directly from the database using the Uniprot identifier? Access to structures can be achieved using:

https://alphafold.ebi.ac.uk/files/AF-" + pdbid + "-F1-model_v1.pdb

I saw that icn3d viewer has it already integrated. See:
https://github.com/ncbi/icn3d/search?q=alphafold

**Comment by fredludlow** [comment]
Yes, this would be great - it would presumably follow the pattern in https://github.com/nglviewer/ngl/blob/master/src/datasource/rcsb-datasource.ts
