### ISSUE TITLE
how to display all the multiple molecules

### ISSUE THREAD

**Issue by worldresize** [nglviewer/ngl#881]
I am using ngl with sdf format. The sdf file contains multiple molecules but ngl only show one. 
My code is :stage.loadFile(url,{defaultRepresentation:true}). My file has been uploaded in txt format.
[Generated_mols_clash (2).txt](https://github.com/nglviewer/ngl/files/7168653/Generated_mols_clash.2.txt)

**Comment by worldresize** [comment]
is there an example of selection with model?

**Comment by fredludlow** [comment]
To select a model (numbered from zero I think) it's a forward slash, e.g. `/0` 

The full selection language docs are here:
https://nglviewer.org/ngl/api/manual/usage/selection-language.html

The `parser/sdf-models` example also shows this
https://nglviewer.org/ngl/?script=parser/sdf-models
