### ISSUE TITLE
How can I get the structural data of residues?

### ISSUE THREAD

**Issue by luanluanxtxm** [nglviewer/ngl#885]
Hello, author
  I now have a requirement as follows:
  The user uploads the pdb file, displays its 3D molecular model on the page, then lists all residues, and finally checks the residue item to add additional residue molecular models to the 3D molecular model.

  At present, I have successfully read the contents of the pdb file and displayed the 3D molecular model through the `stage. loadfile()` method, and then successfully obtained all residue items (`ResidueProxy`) through the `eachResidue()` method. Finally, I found that 3D graphics can be added to the stage through the `addComponentFromObject()` method. However, the parameter structure required by the `addComponentFromObject ()` method is `script | shape | structure | surface | volume`, and I don't know how to get the above data structure from the `ResidueProxy`.

  Can you help me? thank you!

`stage.loadFile(pdb).then(function (o) {
          let residues = [];
          o.structure.eachResidue((x) => {
            residues.push(x.clone());
          });
          setResidues(residues);
          o.addRepresentation("cartoon", { colorScheme: schemeId2 });
          o.autoView();
        });`

`let component = stage.addComponentFromObject(residues[0].structure);
      component.addRepresentation("ball+stick", { colorScheme: schemeId });`

**Comment by luanluanxtxm** [comment]
`Residueproxy.structure` can only get the data structure of the whole pdb file, and what I need now is the data structure of a single residue. After reading the document for a long time, I couldn't find a way. I'm so helpless.

**Comment by fredludlow** [comment]
Apologies if I've misunderstood, are you trying to add new residues to an existing structure, or just display certain residues in a different style?

If it's the first, then be aware that editing structures sort of works, but as it wasn't one of the original design goals you get some odd bugs (a lot of internal code assumes the number and type of atoms and their bonding never changes)

If it's just displaying "all the protein in cartoon, and some of it in ball+stick" then that's much simpler - NGL uses the concept of a selection to decide what is shown for each representation, see this example:
https://codepen.io/fludlow/pen/oNwQyWM

```javascript
let ballStickRepr

// Load PDB entry 1CRN
stage.loadFile( "rcsb://1crn", { defaultRepresentation: false } ).then(c => {
    // Start with a cartoon (whole molecule) and a ball and stick representation (residues 1-3)
    c.addRepresentation('cartoon')
    ballStickRepr = c.addRepresentation('ball+stick', {sele: '1-3'})
    c.autoView('1-3')
    
    // Later, changing selection, this would be in response to user action in your case
    window.setTimeout(() => {
        ballStickRepr.setSelection('1-5')
    }, 3000)
});



```
