### ISSUE TITLE
Changing the default tooltip?

### ISSUE THREAD

**Issue by worldresize** [nglviewer/ngl#891]
Hello author,
I want to change the default tooltip when load the viewport but i only find "tooltip:false" usage. Is there a way to change the tooltip info when loading the nglview like changing the file_name?
Thanks!

**Comment by fredludlow** [comment]
The ligand_viewer example makes a custom tooltip: https://github.com/nglviewer/ngl/blob/4ab8753c38995da675e9efcae2291a298948ccca/examples/scripts/interactive/ligand-viewer.js

**Comment by pguillem** [comment]
Hi all,

Is there a way to redeclare/override/detatch/remove the default tooltip? 
From the link provided by @fredludlow I found 

`stage.mouseControls.remove('hoverPick')`

However this removes the hover action. Also if I add a new tooltip using the hover signal object, it'll just show both at the same time (new on top of the old one).

Is there like an iterator to show/control the signals and tooltips?

Sorry for the hassle. I just don't know enough about the NGL structures/methods yet and the examples in the manual don't show much usage on all the methods.

Thanks in advance
Pedro

**Comment by ppillot** [comment]
The tooltip is not part of NGL library: there is no widget in the library to display a tooltip.
You have to manually bind the information from the hovered signal to whatever element you want on the page.

You have multiple signals in NGL. You can subscribe to them by adding your own callbacks.
