### ISSUE TITLE
Is there a way to add new attributes to atom? 

### ISSUE THREAD

**Issue by appassionate** [nglviewer/ngl#892]
Hi, I want to present my data in every atom
I imaged a customized colorscheme will read the value of  atoms if i can do this successfully.

It might exist in NGL:   ```atom.resno```
can I get ```atoms._input_value``` in NGL?
Thanks!

**Comment by ppillot** [comment]
The list of fields in the atomStore is preconfigured.
To achieve a coloring per external property as you are mentioning, I've created a colorMaker that polls values from a separate data structure.

```typescript
    class MyColorMaker extends NGL.Colormaker {
            myScale: ColormakerScale;

            constructor (params: any) {
                super(params);
                this.parameters.scale = 'OrRd';
                this.parameters.domain = [lMin, lMax];
                this.myScale = this.getScale();
            }
            atomColor (a: AtomProxy) {
                const val =myDataStore[a.serial];
                return (val !== -1) ? this.myScale(val) : 0xcccccc;
            }
    }

        NGLColormakerRegistry.add('mycolor', myColorMaker);

```

**Comment by ppillot** [comment]
The list of fields is preconfigured.
What you can do is create a ColorMaker that will poll values from your own data structure based on the atom id.

**Comment by appassionate** [comment]
> The list of fields is preconfigured. What you can do is create a ColorMaker that will poll values from your own data structure based on the atom id. https://nglviewer.org/ngl/api/manual/coloring.html#custom-coloring

thanks! actually, i'm nglview user. Maybe it will be easier to add my data using this function, but in python console i have no idea about to trans by numpy numerical array to a data in a TS or JS form...
A trick thinking is that if i can update specific color in an exist representation just as adding a reprensentation by ```sele= "@1","@2","@3"```. Or a presentation just owns a colorscheme?  thank you : )

**Comment by hainm** [comment]
@appassionate maybe try to follow those threads in `nglview`:
- https://github.com/nglviewer/nglview/issues/913
- https://github.com/nglviewer/nglview/pull/839

**Comment by fredludlow** [comment]
I do a similar thing (more or less per @ppillot's link, custom class polls data from another source). This gets messier when:

1. The source is async
2. Serializing state (persisting parameters etc) - requires also serializing/reproducing state of the data source

I've been toying with a few ways around this and wondered whether having a general method for passing data through to custom colormakers would be useful? I think it would make a few things I do less verbose as no custom colormaker would be required, just some paramters.

```typescript
export interface ColormakerParameters extends ScaleParameters {
  structure?: Structure
  volume?: Volume
  surface?: Surface
  data?: any  // 
}
```

This would make use of all the existing code around updating a representation with new data (i.e. `setParameters({colorData: someNewData})`. 

More formally, it might be nice to tie the type down a bit more than just `any` (maybe have optional `atomData: { [atomIndex: number]: number}`, `bondData`), these could work with a `StructureDataColorMaker`...

All thoughts and discussion welcome!

**Comment by appassionate** [comment]
merry xmas!
Thanks those consideration. "colormaker” will contain rendering performance optimization...?  i guess. As a python user, i know less about it... : ) A single structure can be imaged, it will be suitable to render a trajectory? Thanks.

**Comment by fredludlow** [comment]
Colormakers are the mechanism by which NGL generates color values for rendering (for single structures or trajectories). If you're just passing in an array of values (one per atom index) then the performance would be comparable to e.g. coloring by bfactor. 

If the values are static across the whole trajectory, then I think it should "just work" after this is merged, with no hit to performance. If the values (and therefore colors) are changing per-frame, then it might require another few changes, but should be feasible, is that the case?

**Comment by appassionate** [comment]
> Colormakers are the mechanism by which NGL generates color values for rendering (for single structures or trajectories). If you're just passing in an array of values (one per atom index) then the performance would be comparable to e.g. coloring by bfactor.
> 
> If the values are static across the whole trajectory, then I think it should "just work" after this is merged, with no hit to performance. If the values (and therefore colors) are changing per-frame, then it might require another few changes, but should be feasible, is that the case?

Yes, I agree.  If value changing per-frame, I guess it will need some "stream reading" process. I think NGL must have finished those topic, for nglviewe can visualize MDAnalysis trajectory (which is a "stream-like reading" package).  
"Original" trajectory information have been loaded by a file in a format. And the **data** "containing information per frame" might be extra, i guess..

**Comment by fredludlow** [comment]
@appassionate - I'm going to close this for now, but please feel free to re-open if you want to revisit it.
