### ISSUE TITLE
Mousewheel Zoom Out focus issue

### ISSUE THREAD

**Issue by sumodhnair19** [nglviewer/ngl#895]
Hi,

I am facing an issue related to focus when user tries to mouse-wheel zoom in/out. For e.g When I try to use mouse wheel zoom In/Out on the container holding the 3D visualisation, it loses its focus considering the body has other containers following it which in turn adds an overflow to the parent container. Basically, the whole body starts to scroll down or up instead of the visualisation. I was wondering if there is anyway I can lock the focus on the viewer while user is performing actions?

I have added a codepen for your reference. Please let me know. 

https://codepen.io/sumodhnair/pen/MWEeYaq?editors=1000

Regards,
Sumodh

**Comment by fredludlow** [comment]
Is #878 relevant? TL;DR is: listen for scroll and preventDefault if it's within the viewer

**Comment by sumodhnair19** [comment]
thanks @fredludlow. It has fixed the issue. However, chrome is throwing an intervention error:  Unable to preventDefault inside passive event listener due to target being treated as passive.

**Comment by fredludlow** [comment]
Assuming you're following the method in the linked issue - you should be setting `passive:false` when you add the event listener. (If you're doing that and it's still not working could you share another codepen to reproduce it please?)

**Comment by fredludlow** [comment]
Hmm, I didn't really get to the bottom of this when you posted it, and looking quickly now can only see these docs that say you can't call `preventDefault` inside a wheel handler on window (or other top-level bits of the DOM)
https://chromestatus.com/feature/6662647093133312

Did you resolve it? (I'm going to close as this is old, but re-open if wanted)
