### ISSUE TITLE
How can find distance between pdf and sdf files through picking ?

### ISSUE THREAD

**Issue by seongsangcho-hits** [nglviewer/ngl#896]
I want to upload pdb and sdf files respectively and find the distance between them by selecting the atoms of each other.

However, it seems that only the atoms in each file can be selected, and the interatomic distance between different files (sdf, pdb) cannot be measured.

How to solve this problem?

```js
// pdb loadFile
    stageRef.current
      .loadFile(fileData, { name: "receptor.pdb", ext: "pdb" })
      .then(function (o) {
        o.addRepresentation("cartoon");
        o.autoView();
      });

//sdf load FIle
      stageRef.current.loadFile(files[0]).then(function (o) {
        o.addRepresentation("ball+stick");
      });
```

**Comment by fredludlow** [comment]
There's no simple general workaround for this unfortunately. The problem is distance representations only apply to a single structure (file). However, you can concatenate two structures into a new one and display that, the test/concat example should get you started:
https://github.com/nglviewer/ngl/blob/master/examples/scripts/test/concat.js

**Comment by seongsangcho-hits** [comment]
@fredludlow  Thanks. I tried to use that example in my project and it works.
I wanna show to ball+stick only ligand(sdf file). so I used `sele` option.
finally, I can measure distance between sdf and pdb files through picking two point.

It is my code.

```js
      (stageRef.current as any).loadFile(files[0]).then(function (o: any) {
        if (NGL)
          var cs = NGL.concatStructures(
            "concat",
            o.structure.getView(new NGL.Selection("")),
            (stageRef.current as any as any).redPandas.structure.getView(
              new NGL.Selection(""),
            ),
          );
        var comp = (stageRef.current as any).addComponentFromObject(cs);
        comp.addRepresentation("ball+stick", { sele: "ligand" });
        comp.addRepresentation("cartoon");
        o.autoView();
      });
```

**Comment by fredludlow** [comment]
@seongsangcho-hits - I received an email notification of your reply but I can't see it on this page (some caching thing at github, or maybe it got deleted?) Anyway, glad it worked!
