### ISSUE TITLE
Error with binds

### ISSUE THREAD

**Issue by ixdi** [nglviewer/ngl#898]
Hi,

When viewing a polymer like the attached file with the NGL viewer the links are not represented.

[polymer.gro.zip](https://github.com/nglviewer/ngl/files/7726290/polymer.gro.zip)

Any idea what is happening? Is it a NGL error?

Thanks

**Comment by fredludlow** [comment]
There's a message printed to the console when you load that file about a residue having more than 500 atoms (and therefore NGL skipping autobonding). Can you assign some appropriate residue numbers (it looks like a poly-ester - maybe increment the residue number each time you get back to O1?)

**Comment by ixdi** [comment]
Thank you, that is!
