### ISSUE TITLE
Building ngl without three.js

### ISSUE THREAD

**Issue by Oeffner** [nglviewer/ngl#913]
From what I understand this should be possible to do with after Release 2.0.0-dev.38 but how?
In an empty directory I clone the ngl repo, set the environment variable `NGL_EXTERNAL_THREEJS=1`, then issue the commands 
`npm install ngl`
`npm run-script build`
which  produces `build/js/ngl.dev.js`. 
I assumed that in my own project (html code that uses NGL for displaying graphics) using ngl.dev.js would cause an error unless I also imported three.js into my own project. But this is not the case so I guess three.js is still built into ngl. Is it not possible to have an external reference to three.js from ngl?
Sorry if this has already been answered in the past but I have been unable to solve this problem for some time.
Many thanks.

**Comment by fredludlow** [comment]
Are you using script tags or a module bundler/builder?

`npm run build` will create the files under the build directory (un-minified)
`npm run build-min` will create 3 pairs (js and map) under the dist folder (minified)

In each case these come in 3 flavours:

* `ngl.esm.js` - ES6 module format (includes `import` syntax) with no other deps bundled in, assumes the browser or bundler supports the import syntax and can find the dependencies

* `ngl.umd.js` - 'UMD' module format, can be included directly in the browser with a `<script>` tag or using `require` from within node tag but also does not contain dependencies like three.js, it assumes they're available (i.e. a previous <script> tag or installed in node_modules for node) - it's also really quirky with the way it expects these to be named, I think for historic reasons, though probably now would be a good time to clear this up with a simple example.

* `ngl[.dev].js` - This has all dependencies bundle in and can be included with a <script> tag

**Comment by fredludlow** [comment]
If you're using rollup (or webpack, or whatever) to build your app and you want to include NGL directly into your built code (using three.js 0.118, later versions may not be compatible with NGL or may require updates in NGL) then you could try something like:

* Clone NGL, `npm install`, `npm build-min`.
* In your project's package.json depedencies list `"ngl": "/path/to/your/working/copy"`
* In your code `import { Stage } from 'ngl'`

If you want three.js 119 onwards you *may* need to update some of NGL as three.js doesn't preserve backwards compatibility between minor versions in 0.x (this is consistent with semver AIUI). If you're creating a node package you'll need to make sure the three.js versions specified are compatible between your code and NGL otherwise npm will just grab two copies (one for your code, one for NGL)

If you're using script tags it gets a bit more cumbersome, this works from current master but if you want to do it this way let's get this fixed, for now:
```html
  <script src="https://unpkg.com/signals@1.0.0/dist/signals.js"></script>
  <script src="https://unpkg.com/three@0.118.0/build/three.js"></script>
  <script src="https://unpkg.com/chroma-js@1.3.7/chroma.min.js"></script>
  <script>
    window.three = window.THREE
    window.signalsWrapper = window.signals
  </script>
  <script src="/path/to/ngl.umd.js"></script>
```


Sorry, that's all a bit of a brain dump, if you tell me more about your specific case I can try and provide more specific information!

**Comment by Oeffner** [comment]
Thanks a lot for the elaborate replies. I shall give that a go and will let you know. I've spent the past few days trying to educate myself about node.js and npm as this must be the way forward for me.

**Comment by Oeffner** [comment]
Thanks a lot @fredludlow for the pointers. So far I'm using three.js via script tags as you suggested above which does seem to allow me having both ngl objects and THREE objects together in the same scene. 
But I am struggling to get a THREE object to respond to mouse action. In the example below I can move, rotate or zoom the molecule around with mouse buttons. The THREE sphere however only responds to zoom action, like mouse click+shift key. I guess there must be an ngl mouse event handler that also needs to handle the THREE object. 

    <script src="signals.js" type="text/javascript"></script>
    <script src="three.min.js" type="text/javascript"></script>
    <script src="chroma.min.js" type="text/javascript"></script>
    <script>
        window.three = window.THREE
        window.signalsWrapper = window.signals
    </script>
    <script src="ngl.umd.js" type="text/javascript"></script>

    <script>

        var stage;
        document.addEventListener("DOMContentLoaded", function () {
            stage = new NGL.Stage("viewport", {
                backgroundColor: "grey",
                cameraType: "orthographic",
            });

            stage.loadFile("rcsb://1mbn").then(function (o) {
                o.addRepresentation("cartoon");
                o.autoView();
            });

            var mysphere = new THREE.Mesh(new THREE.SphereGeometry(1.0, 20, 20),
                new THREE.MeshStandardMaterial());
            mysphere.position.set( 8.0, 0.0, 5.0)
            mysphere.scale.x = 3.0;
            mysphere.scale.y = 3.0;
            mysphere.scale.z = 3.0;
            mysphere.position.needsUpdate = true;
            stage.viewer.scene.add(mysphere);
        })

        window.addEventListener("resize", function (event) { stage.handleResize(); }, false);

    </script>

**Comment by garyo** [comment]
If you just want your sphere to be "part of the scene" and rotate around with the molecule, then instead of adding it to the top level of the scene, add it to `scene.rotationGroup.translationGroup`.

**Comment by Oeffner** [comment]
Thanks a lot @garyo, I change the line to `stage.viewer.scene.getObjectByName("translationGroup").add(isphere);` which did the trick. Now my Three spheres are moving together with the rest of the stage objects.

The actual goal was to investigate if I could use THREE.Frustum() to see if objects are being rendered or not as in https://stackoverflow.com/questions/17624021/determine-if-a-mesh-is-visible-on-the-viewport-according-to-current-camera but that seems to ignore whatever I set stage.viewer.parameters.clipNear or stage.viewer.parameters.clipFar to be. So yielding false positives when obejcts are not visible.
