### ISSUE TITLE
Extra bond displayed

### ISSUE THREAD

**Issue by hainm** [nglviewer/ngl#914]
Dear all,

`nglview` user reported this [issue](https://github.com/nglviewer/nglview/issues/1013) but I think it's more about `NGL`. The pdb id is `3fgu` (For unknown reason, I could not fetch the image from NGL webapp anymore).

Cheers
Hai

**Comment by fredludlow** [comment]
I couldn't reproduce it here when I just tried: http://nglviewer.org/ngl/ - were you trying with that one or a different URL?

**Comment by hainm** [comment]
> 3fgu

hi @fredludlow: originally I could not load the pdb file to `NGL` (may be because I use NGL in igcognito mode in chrome?) so I used `nglview`.  I guess `nglview` is using the older version of NGL.

Thank you.
