### ISSUE TITLE
Loading of mmtf fails with sd.xCoordList is undefined

### ISSUE THREAD

**Issue by fredricj** [nglviewer/ngl#919]
Using the example viewer, I get this error in the console when attempting to load mmtf files retrieved from rcsb:
 STAGE LOG error loading file: 'TypeError: sd.xCoordList is undefined'  (stage.ts:278:12)

Example files not working: https://mmtf.rcsb.org/v1.0/full/7N4N  and  https://mmtf.rcsb.org/v1.0/full/6HT7
Files converted from pdb to mmtf with BioUtils.jar works fine so far.

I'm using the current latest version in git (b3769239)

**Comment by fredludlow** [comment]
I can't reproduce with latest master? Was this a temporary issue with a particular build/rcsb files/corrupted version cached somewhere etc, or are you still seeing it?

**Comment by fredricj** [comment]
Revisiting this issue again. Sorry for the delay in response.
The issue occurred because the files I tried to open was in mmtf.gz instead of uncompressed. I only figured this out now when the file I downloaded in the browser could be opened in the example webapp while the one I downloaded with curl didn't and was much smaller.
