### ISSUE TITLE
help with broken .cif file?

### ISSUE THREAD

**Issue by colin-combe** [nglviewer/ngl#932]
Hi,
is anyone able to help identify the problem with the attached .cif file, I'm told it opens in Chimera.
In NGL it gives the message:
`Uncaught (in promise) error loading file: 'TypeError: Cannot read properties of undefined (reading 'replace')'`
thanks,
Colin

[pdb_extract_20903.cif.txt](https://github.com/nglviewer/ngl/files/8850660/pdb_extract_20903.cif.txt)

**Comment by fredludlow** [comment]
Closing as this is pretty old - please re-open if still an issue (or if someone comes up against a similar thing)
