### ISSUE TITLE
Is there a way for mol2 file to display aromatic rings?

### ISSUE THREAD

**Issue by QDMarkMan** [nglviewer/ngl#937]
Hey guys. Is there a way for mol2 file to display aromatic rings like the picture below?

![image](https://user-images.githubusercontent.com/18100675/182105275-9dc81835-ed33-48da-b1b2-67d029cb7b4c.png)

**Comment by fredludlow** [comment]
No, currently aromatic bonds are parsed as single bonds. If you can kekulize the structure first you'll get the alternating single/double bonds which obviously isn't exactly the same, but may be a useful workaround for you.

**Comment by QDMarkMan** [comment]
> 

Thank you very much. By the way , Does ngl have built-in support kekulize mol2 structure ?

**Comment by fredludlow** [comment]
Not that I'm aware of. I'd look at rdkit (or openbabel)
