### ISSUE TITLE
Subscription to render completion 

### ISSUE THREAD

**Issue by StLeonidas** [nglviewer/ngl#945]
Thanks a lot for great tool!
Could you advise if there is a way to subscribe event responsible for rendering completion?

**Comment by fredludlow** [comment]
NGL mostly uses the [signals](https://millermedeiros.github.io/js-signals/docs/symbols/Signal.html) library internally.

You can access a `ticked` (fired before rendering) and a `rendered` (after rendering) signal via `stage.viewer.signals.ticked` or `stage.viewer.signals.rendered`, 

If you want to dig in the code it's around here: 
https://github.com/nglviewer/ngl/blob/138fa2cbe469bf9277d8d42cde2977976e14a1cc/src/viewer/viewer.ts#L999-L1014

So, something like `stage.viewer.signals.rendered.add(yourCallback)` ought to fire after each render.

**Comment by StLeonidas** [comment]
Thanks a lot!
