### ISSUE TITLE
NGL shows white color for this cif

### ISSUE THREAD

**Issue by hainm** [nglviewer/ngl#950]
Dear all, how are you doing?

One of `nglview`'s users gets issue with color of his cif file (I am attaching here).

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/4451957/206934976-97a70880-80d0-4e84-a1da-0228f0d1292f.png">

[V4GaSe8.cif.txt](https://github.com/nglviewer/ngl/files/10203546/V4GaSe8.cif.txt)

Do you have any suggestion? Thanks
PS: nglview issue is here: https://github.com/nglviewer/nglview/issues/1039

**Comment by ppillot** [comment]
White is the default element color when the element is unrecognized.
I have had a look at the parser code for core CIF files (i.e. not mmCIF files) and it appears that the element name is taken from `_atom_site_type_symbol` without processing.
In the case of the file you provided, that means that `V3.25+` will be used as element name in lieu of `V`, and it won't be recognized as a known element further down.
The fix shall be easy to make and we may as well infer the formal charge value (though it might be preferable to get it from the `_atom_type` loop)

**Comment by hainm** [comment]
Thanks @ppillot

**Comment by ppillot** [comment]
Fixed:
<img width="804" alt="image" src="https://github.com/nglviewer/ngl/assets/3930632/2c64cd67-7300-4439-8122-e1d417b843b1">
