### ISSUE TITLE
How to convert the coordinates of 8 points of a cube into a BoxBuffer

### ISSUE THREAD

**Issue by flybirdGit** [nglviewer/ngl#956]
I want to generate the corresponding box based on the 8 point coordinates of the cube, but I don't know how to use this data to generate the corresponding NGL.BoxBuffer, especially the meaning of the parameters of this object, postion, size, heightAxis, depthAxis. I need your help.

**Comment by ppillot** [comment]
I encountered the same issue I guess when I wanted to draw a cube in 3D and finally created a shape based on meshes instead that is defining triangles vertices for each face of the cube (that's 36 vertices for a total of 12 triangles, 2 per face of the cube). Others might know how to use the BoxBuffer instead?

**Comment by flybirdGit** [comment]
Thanks for your help, so how about using NGL to draw a spatial triangle based on the coordinates of three points, that sounds like a good solution

**Comment by flybirdGit** [comment]
Thank you again for your help, which solved the problem I was facing perfectly.
