### ISSUE TITLE
Remove('clickPick')

### ISSUE THREAD

**Issue by ashipiling** [nglviewer/ngl#965]
Hello,
I am trying to turn off the function that camera will move to the atom after clicking on the atom. I tried "stage.mouseControls.remove('clickPick')", but it failed. 
How could I do that?

**Comment by ppillot** [comment]
I am using the following `stage.mouseControls.remove('clickPick-left', MouseActions.movePick);`
(MouseActions is imported from the NGL module, but I think you can omit it all together)

**Comment by ashipiling** [comment]
thanks, 
`stage.mouseControls.remove('clickPick-left')` is ok!
